const editor=document.querySelector('#editor');
const titleInput=document.querySelector('#documentTitle');
const saveStatus=document.querySelector('#saveStatus');
const wordCount=document.querySelector('#wordCount');
const charCount=document.querySelector('#charCount');
const zoomRange=document.querySelector('#zoomRange');
const zoomValue=document.querySelector('#zoomValue');
const toast=document.querySelector('#toast');
const STORAGE_KEY='myword2026-document';
const HISTORY_KEY='myword2026-history';
const DOCUMENTS_KEY='myword2026-documents';
const CUSTOM_TEMPLATE_KEY='myword2026-custom-template';
let saveTimer;
let savedRange=null;
let selectedImage=null;
let activeTableCell=null;
let trackChanges=false;
let applyingTrackedInput=false;
let copiedTextStyle='';
let wordGoal=Number(localStorage.getItem('myword2026-word-goal'))||0;
let documentMeta={author:'',subject:'',keywords:''};
let focusSeconds=0;
let focusTimer=null;

function runCommand(command,value=null){editor.focus();document.execCommand(command,false,value);updateStats();queueAutoSave()}
document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>runCommand(button.dataset.command)));
document.querySelector('#fontName').addEventListener('change',e=>runCommand('fontName',e.target.value));
document.querySelector('#fontSize').addEventListener('change',e=>runCommand('fontSize',e.target.value));
document.querySelector('#textColor').addEventListener('input',e=>runCommand('foreColor',e.target.value));
document.querySelector('#highlightColor').addEventListener('input',e=>runCommand('hiliteColor',e.target.value));
document.querySelector('#blockFormat').addEventListener('change',e=>runCommand('formatBlock',e.target.value));

function getPlainText(){return editor.innerText.replace(/\u00a0/g,' ').trim()}
function updateStats(){const text=getPlainText();const words=text?text.split(/\s+/).length:0;wordCount.textContent=`Слов: ${words}`;charCount.textContent=`Знаков: ${text.length}`;document.querySelector('#readingTime').textContent=`Чтение: ${words<180?'менее 1':Math.ceil(words/180)} мин`;document.querySelector('#pageCount').textContent=`Страниц примерно: ${Math.max(1,Math.ceil(editor.scrollHeight/1123))}`;document.querySelector('#goalStatus').textContent=wordGoal?`Цель: ${words} / ${wordGoal}`:'Цель: не задана';document.querySelector('#goalProgressBar').style.width=`${wordGoal?Math.min(100,words/wordGoal*100):0}%`}
function getDocumentData(){return{app:'MyWord 2026',version:15,title:titleInput.value,html:editor.innerHTML,margins:document.querySelector('#marginSelect').value,orientation:document.querySelector('#orientationSelect').value,pageSize:document.querySelector('#pageSizeSelect').value,pageColor:document.querySelector('#pageColor').value,columns:Number(document.querySelector('#columnsSelect').value),watermark:editor.dataset.watermark||'',pageBorder:editor.classList.contains('page-border'),wordGoal,meta:documentMeta,language:editor.lang||'ru-RU'}}
function queueAutoSave(){saveStatus.textContent='Сохранение…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(getDocumentData()));saveStatus.textContent='Документ сохранён'},500)}
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
editor.addEventListener('input',()=>{updateStats();updateOutline();queueAutoSave()});
editor.addEventListener('beforeinput',event=>{if(!trackChanges||applyingTrackedInput||event.inputType!=='insertText'||!event.data)return;event.preventDefault();applyingTrackedInput=true;document.execCommand('insertHTML',false,`<span class="tracked-insert">${escapeHtml(event.data)}</span>`);applyingTrackedInput=false;updateStats();queueAutoSave()});
editor.addEventListener('mouseup',rememberSelection);editor.addEventListener('keyup',rememberSelection);
editor.addEventListener('click',event=>{document.querySelectorAll('.image-selected').forEach(img=>img.classList.remove('image-selected'));if(event.target.tagName==='IMG'){selectedImage=event.target;selectedImage.classList.add('image-selected');document.querySelector('#imageToolbar').classList.remove('hidden')}else{selectedImage=null;document.querySelector('#imageToolbar').classList.add('hidden')}activeTableCell=event.target.closest('td,th')});
titleInput.addEventListener('input',()=>{document.querySelector('.window-title').textContent=titleInput.value||'Документ1';queueAutoSave()});

document.querySelector('#newButton').addEventListener('click',()=>{if(!confirm('Создать новый документ? Текущий текст будет заменён.'))return;titleInput.value='Новый документ';editor.innerHTML='<h1>Новый документ</h1><p>Начните писать здесь…</p>';queueAutoSave();updateStats()});
const templates={blank:{title:'Новый документ',html:'<h1>Новый документ</h1><p>Начните писать здесь…</p>'},resume:{title:'Моё резюме',html:'<h1>Имя и фамилия</h1><p><b>Телефон:</b> +7 ___ ___ __ __ · <b>Email:</b> example@mail.com</p><hr><h2>О себе</h2><p>Кратко расскажите о себе и своих профессиональных качествах.</p><h2>Опыт работы</h2><h3>Название компании — должность</h3><p>Период работы</p><ul><li>Основные обязанности и достижения</li></ul><h2>Навыки</h2><ul><li>Навык 1</li><li>Навык 2</li></ul>'},letter:{title:'Деловое письмо',html:'<p style="text-align:right">Дата: __.__.2026</p><p><b>Кому:</b> Имя получателя<br><b>От:</b> Имя отправителя</p><h1>Тема письма</h1><p>Уважаемый(ая) …!</p><p>Основной текст делового письма.</p><p>С уважением,<br><b>Имя и фамилия</b></p>'},report:{title:'Отчёт',html:'<h1>Отчёт</h1><p><b>Период:</b> __________<br><b>Ответственный:</b> __________</p><h2>1. Основная информация</h2><p>Введите информацию.</p><h2>2. Выполненная работа</h2><ul><li>Пункт 1</li><li>Пункт 2</li></ul><h2>3. Результаты</h2><p>Опишите результаты.</p><h2>4. Вывод</h2><p>Введите итоговый вывод.</p>'}};
Object.assign(templates,{notes:{title:'Заметки',html:'<h1>Заметки</h1><p><b>Дата:</b> __________</p><h2>Главная мысль</h2><p>Введите заметку…</p><h2>Следующие действия</h2><div class="check-item"><input type="checkbox"><span>Новая задача</span></div>'},calendar:{title:'Календарь',html:'<h1>Календарь месяца</h1><table><tr><th>Пн</th><th>Вт</th><th>Ср</th><th>Чт</th><th>Пт</th><th>Сб</th><th>Вс</th></tr><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td></tr><tr><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td><td>13</td><td>14</td></tr></table>'},checklist:{title:'Список задач',html:'<h1>Список задач</h1><p><b>Период:</b> __________</p><div class="check-item"><input type="checkbox"><span>Первая задача</span></div><div class="check-item"><input type="checkbox"><span>Вторая задача</span></div><div class="check-item"><input type="checkbox"><span>Третья задача</span></div>'},journal:{title:'Мой журнал',html:'<h1>Мой журнал</h1><p><b>Дата:</b> __________ &nbsp; <b>Настроение:</b> __________</p><h2>События дня</h2><p>Расскажите, как прошёл день…</p><h2>Важные мысли</h2><p>Введите текст…</p>'},newsletter:{title:'Информационный бюллетень',html:'<h1 style="color:#16a34a">ИНФОРМАЦИОННЫЙ БЮЛЛЕТЕНЬ</h1><p><b>Выпуск №1 · 2026</b></p><hr><h2>Главная новость</h2><p>Краткое описание главной новости.</p><h2>Другие события</h2><p>Введите информацию…</p>'},brochure:{title:'Буклет',html:'<h1 style="text-align:center;color:#7c3aed">ЗАГОЛОВОК БУКЛЕТА</h1><p style="text-align:center"><b>Краткое описание</b></p><hr><h2>О нас</h2><p>Расскажите о компании или проекте.</p><h2>Наши преимущества</h2><ul><li>Преимущество 1</li><li>Преимущество 2</li></ul><h2>Контакты</h2><p>Телефон: __________</p>'}});
document.querySelector('#templatesButton').addEventListener('click',()=>document.querySelector('#templatesModal').classList.remove('hidden'));document.querySelector('#closeTemplatesButton').addEventListener('click',()=>document.querySelector('#templatesModal').classList.add('hidden'));document.querySelector('#templatesModal').addEventListener('click',e=>{if(e.target.id==='templatesModal')e.currentTarget.classList.add('hidden')});document.querySelectorAll('[data-template]').forEach(button=>button.addEventListener('click',()=>{if(getPlainText()&&!confirm('Заменить текущий документ выбранным шаблоном?'))return;const template=templates[button.dataset.template];titleInput.value=template.title;editor.innerHTML=template.html;document.querySelector('#templatesModal').classList.add('hidden');updateStats();updateOutline();queueAutoSave();showToast('Шаблон применён')}));
document.querySelector('#saveButton').addEventListener('click',()=>{const file=`<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>${escapeHtml(titleInput.value)}</title><style>body{max-width:760px;margin:50px auto;padding:30px;font-family:Calibri,Arial,sans-serif;line-height:1.55}</style></head><body>${editor.innerHTML}</body></html>`;downloadFile(file,safeName(titleInput.value)+'.html','text/html');showToast('Документ сохранён в формате HTML')});
document.querySelector('#projectButton').addEventListener('click',()=>{downloadFile(JSON.stringify(getDocumentData(),null,2),safeName(titleInput.value)+'.myword.json','application/json');showToast('Проект сохранён со всеми настройками')});
document.querySelector('#saveCopyButton').addEventListener('click',()=>{const stamp=new Date().toISOString().slice(0,16).replace(/[T:]/g,'-');downloadFile(JSON.stringify(getDocumentData(),null,2),`${safeName(titleInput.value)}-копия-${stamp}.myword.json`,'application/json');showToast('Отдельная копия сохранена')});
document.querySelector('#lockedButton').addEventListener('click',async()=>{if(!globalThis.crypto?.subtle){showToast('Шифрование недоступно в этом режиме браузера');return}const password=prompt('Придумайте пароль для файла:');if(!password||password.length<4){showToast('Пароль должен содержать минимум 4 символа');return}try{const encrypted=await encryptProject(getDocumentData(),password);downloadFile(JSON.stringify(encrypted),safeName(titleInput.value)+'.myword.locked','application/json');showToast('Защищённый файл сохранён')}catch{showToast('Не удалось зашифровать документ')}});
async function passwordKey(password,salt,usage){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,[usage])}
function toBase64(bytes){const array=new Uint8Array(bytes);let binary='';for(let index=0;index<array.length;index+=32768)binary+=String.fromCharCode(...array.subarray(index,index+32768));return btoa(binary)}const fromBase64=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
async function encryptProject(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await passwordKey(password,salt,'encrypt'),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(data)));return{app:'MyWord Locked',salt:toBase64(salt),iv:toBase64(iv),data:toBase64(cipher)}}
async function decryptProject(payload,password){const salt=fromBase64(payload.salt),iv=fromBase64(payload.iv),key=await passwordKey(password,salt,'decrypt'),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,fromBase64(payload.data));return JSON.parse(new TextDecoder().decode(plain))}
document.querySelector('#documentsButton').addEventListener('click',()=>{renderDocuments();document.querySelector('#documentsModal').classList.remove('hidden')});document.querySelector('#closeDocumentsButton').addEventListener('click',()=>document.querySelector('#documentsModal').classList.add('hidden'));document.querySelector('#saveBrowserDocumentButton').addEventListener('click',()=>{const docs=getBrowserDocuments(),data=getDocumentData();docs.unshift({...data,id:Date.now(),savedAt:new Date().toISOString()});localStorage.setItem(DOCUMENTS_KEY,JSON.stringify(docs.slice(0,20)));renderDocuments();showToast('Документ сохранён в браузере')});
function getBrowserDocuments(){try{return JSON.parse(localStorage.getItem(DOCUMENTS_KEY))||[]}catch{return[]}}function renderDocuments(){const list=document.querySelector('#documentsList'),docs=getBrowserDocuments();list.innerHTML=docs.length?'':'<div class="history-empty">Сохранённых документов пока нет.</div>';docs.forEach((doc,index)=>{const row=document.createElement('div');row.className='history-item';row.innerHTML=`<div><strong>${escapeHtml(doc.title)}</strong><span>${new Date(doc.savedAt).toLocaleString('ru-RU')}</span></div><button data-doc-open="${index}">Открыть</button><button data-doc-delete="${index}">×</button>`;list.append(row)});list.querySelectorAll('[data-doc-open]').forEach(button=>button.onclick=()=>{loadDocumentData(getBrowserDocuments()[button.dataset.docOpen]);document.querySelector('#documentsModal').classList.add('hidden')});list.querySelectorAll('[data-doc-delete]').forEach(button=>button.onclick=()=>{const docs=getBrowserDocuments();docs.splice(button.dataset.docDelete,1);localStorage.setItem(DOCUMENTS_KEY,JSON.stringify(docs));renderDocuments()})}
document.querySelector('#saveCustomTemplateButton').addEventListener('click',()=>{localStorage.setItem(CUSTOM_TEMPLATE_KEY,JSON.stringify(getDocumentData()));showToast('Собственный шаблон сохранён')});
document.querySelector('#customTemplateButton').addEventListener('click',()=>{const saved=localStorage.getItem(CUSTOM_TEMPLATE_KEY);if(!saved){showToast('Сначала сохраните собственный шаблон');return}if(getPlainText()&&!confirm('Заменить текущий документ вашим шаблоном?'))return;try{loadDocumentData(JSON.parse(saved));document.querySelector('#templatesModal').classList.add('hidden');showToast('Ваш шаблон применён')}catch{showToast('Не удалось открыть шаблон')}});
document.querySelector('#historyButton').addEventListener('click',()=>{renderHistory();document.querySelector('#historyModal').classList.remove('hidden')});
document.querySelector('#closeHistoryButton').addEventListener('click',()=>document.querySelector('#historyModal').classList.add('hidden'));
document.querySelector('#historyModal').addEventListener('click',event=>{if(event.target.id==='historyModal')event.currentTarget.classList.add('hidden')});
document.querySelector('#saveVersionButton').addEventListener('click',()=>saveVersion());
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY))||[]}catch{return[]}}
function saveVersion(){const history=getHistory(),data=getDocumentData();if(history[0]?.html===data.html&&history[0]?.title===data.title){showToast('Документ не изменился');return}history.unshift({...data,savedAt:new Date().toISOString()});localStorage.setItem(HISTORY_KEY,JSON.stringify(history.slice(0,12)));renderHistory();showToast('Версия сохранена')}
function renderHistory(){const list=document.querySelector('#historyList'),history=getHistory();if(!history.length){list.innerHTML='<div class="history-empty">Сохранённых версий пока нет.</div>';return}list.innerHTML='';history.forEach((item,index)=>{const row=document.createElement('div');row.className='history-item';row.innerHTML=`<div><strong>${escapeHtml(item.title||'Документ')}</strong><span>${new Date(item.savedAt).toLocaleString('ru-RU')}</span></div><button data-restore="${index}">Восстановить</button><button data-remove="${index}">×</button>`;list.append(row)});list.querySelectorAll('[data-restore]').forEach(button=>button.onclick=()=>{const item=getHistory()[button.dataset.restore];if(!item||!confirm('Восстановить эту версию документа?'))return;titleInput.value=item.title;editor.innerHTML=item.html;applyPageSettings(item.margins,item.orientation,item.pageColor);applyColumns(item.columns||1);applyDocumentExtras(item);queueAutoSave();updateStats();updateOutline();document.querySelector('#historyModal').classList.add('hidden');showToast('Версия восстановлена')});list.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{const history=getHistory();history.splice(button.dataset.remove,1);localStorage.setItem(HISTORY_KEY,JSON.stringify(history));renderHistory()})}
document.querySelector('#txtButton').addEventListener('click',()=>{downloadFile(getPlainText(),safeName(titleInput.value)+'.txt','text/plain');showToast('Текст сохранён в формате TXT')});
document.querySelector('#markdownButton').addEventListener('click',()=>{downloadFile(editorToMarkdown(),safeName(titleInput.value)+'.md','text/markdown');showToast('Документ сохранён в Markdown')});
document.querySelector('#docButton').addEventListener('click',()=>{if(!window.htmlDocx){showToast('Модуль DOCX ещё загружается — повторите через несколько секунд');return}const file=`<!DOCTYPE html><html lang="${editor.lang||'ru'}"><head><meta charset="UTF-8"><title>${escapeHtml(titleInput.value)}</title><style>body{font-family:Calibri,Arial;font-size:12pt;line-height:1.55;margin:2cm}table{border-collapse:collapse;width:100%}td,th{border:1px solid #777;padding:7px}img{max-width:100%}</style></head><body>${editor.innerHTML}</body></html>`;const blob=htmlDocx.asBlob(file,{orientation:'portrait',margins:{top:1134,right:1134,bottom:1134,left:1134}}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=safeName(titleInput.value)+'.docx';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500);showToast('Документ DOCX сохранён')});
document.querySelector('#duplicateButton').addEventListener('click',()=>{const docs=getBrowserDocuments(),data=getDocumentData();docs.unshift({...data,title:`${data.title} — копия`,id:Date.now(),savedAt:new Date().toISOString()});localStorage.setItem(DOCUMENTS_KEY,JSON.stringify(docs.slice(0,20)));showToast('Дубликат сохранён в разделе «Документы»')});
document.querySelector('#openButton').addEventListener('click',()=>document.querySelector('#fileInput').click());
document.querySelector('#fileInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const lower=file.name.toLowerCase(),reader=new FileReader();reader.onload=async()=>{try{if(lower.endsWith('.docx')){if(!window.mammoth)throw Error('DOCX module');const result=await mammoth.convertToHtml({arrayBuffer:reader.result});titleInput.value=file.name.replace(/\.[^.]+$/,'');editor.innerHTML=result.value||'<p></p>'}else if(lower.endsWith('.locked')){const password=prompt('Введите пароль файла:');if(!password)return;loadDocumentData(await decryptProject(JSON.parse(reader.result),password))}else if(lower.endsWith('.json')){const data=JSON.parse(reader.result);if(data.app!=='MyWord 2026')throw Error();loadDocumentData(data)}else{titleInput.value=file.name.replace(/\.[^.]+$/,'');if(lower.endsWith('.txt'))editor.innerText=reader.result;else{const parsed=new DOMParser().parseFromString(reader.result,'text/html');editor.innerHTML=parsed.body.innerHTML}}updateStats();queueAutoSave();showToast(lower.endsWith('.docx')?'Документ Word открыт':'Файл открыт')}catch{showToast('Не удалось открыть файл. Проверьте его формат')}};if(lower.endsWith('.docx'))reader.readAsArrayBuffer(file);else reader.readAsText(file);event.target.value=''});
document.querySelector('#printButton').addEventListener('click',()=>window.print());
document.querySelector('#themeButton').addEventListener('click',event=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');event.currentTarget.textContent=dark?'☀️':'🌙';localStorage.setItem('myword2026-theme',dark?'dark':'light')});
document.querySelector('#speakButton').addEventListener('click',event=>{if(!('speechSynthesis'in window)){showToast('Чтение вслух не поддерживается');return}if(speechSynthesis.speaking){speechSynthesis.cancel();event.currentTarget.classList.remove('speaking');event.currentTarget.textContent='🔊 Читать';return}const selection=window.getSelection(),text=selection&&!selection.isCollapsed&&editor.contains(selection.anchorNode)?selection.toString():getPlainText();if(!text){showToast('В документе нет текста');return}const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ru-RU';utterance.rate=1;utterance.onend=()=>{event.currentTarget.classList.remove('speaking');event.currentTarget.textContent='🔊 Читать'};speechSynthesis.speak(utterance);event.currentTarget.classList.add('speaking');event.currentTarget.textContent='■ Стоп'});
document.querySelector('#focusTimerButton').addEventListener('click',()=>{if(focusTimer){clearInterval(focusTimer);focusTimer=null;focusSeconds=0;updateFocusTimer();showToast('Таймер остановлен');return}const minutes=Math.max(1,Math.min(120,Number(prompt('Сколько минут работать без перерыва?',25))||0));if(!minutes)return;focusSeconds=minutes*60;updateFocusTimer();focusTimer=setInterval(()=>{focusSeconds--;updateFocusTimer();if(focusSeconds<=0){clearInterval(focusTimer);focusTimer=null;showToast('Время закончилось — сделайте перерыв!');document.querySelector('#focusTimerButton').textContent='⏱ 25:00'}},1000);showToast(`Таймер запущен на ${minutes} мин`)});
function updateFocusTimer(){const minutes=Math.floor(focusSeconds/60),seconds=focusSeconds%60,label=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;document.querySelector('#timerStatus').textContent=focusTimer?`Фокус: ${label}`:'';document.querySelector('#focusTimerButton').textContent=focusTimer?`■ ${label}`:'⏱ 25:00'}
document.querySelector('#restoreBackupButton').addEventListener('click',()=>{const saved=localStorage.getItem('myword2026-emergency-backup');if(!saved){showToast('Аварийная копия пока не создана');return}if(!confirm('Восстановить последнюю аварийную копию?'))return;try{loadDocumentData(JSON.parse(saved));showToast('Аварийная копия восстановлена')}catch{showToast('Копия повреждена')}});
document.querySelector('#fullscreenButton').addEventListener('click',()=>{document.body.classList.toggle('focus-mode');if(document.body.classList.contains('focus-mode'))document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.()});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('focus-mode')});
document.querySelectorAll('.tab[data-message]').forEach(tab=>tab.addEventListener('click',()=>showToast(tab.dataset.message)));
zoomRange.addEventListener('input',()=>{const value=zoomRange.value;editor.style.transform=`scale(${value/100})`;editor.parentElement.style.marginBottom=`${1123*(value/100-1)}px`;zoomValue.value=`${value}%`});

function rememberSelection(){const selection=window.getSelection();if(selection.rangeCount&&editor.contains(selection.anchorNode))savedRange=selection.getRangeAt(0).cloneRange()}
function restoreSelection(){editor.focus();if(!savedRange)return;const selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedRange)}
document.querySelector('#imageButton').addEventListener('click',()=>{rememberSelection();document.querySelector('#imageInput').click()});
document.querySelector('#imageInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){showToast('Изображение должно быть меньше 5 МБ');return}const reader=new FileReader();reader.onload=()=>{restoreSelection();document.execCommand('insertImage',false,reader.result);updateStats();queueAutoSave();showToast('Изображение вставлено')};reader.readAsDataURL(file);event.target.value=''});
document.querySelectorAll('[data-image-size]').forEach(button=>button.addEventListener('click',()=>{if(!selectedImage)return;selectedImage.style.width=button.dataset.imageSize;selectedImage.style.height='auto';queueAutoSave()}));document.querySelectorAll('[data-image-align]').forEach(button=>button.addEventListener('click',()=>{if(!selectedImage)return;const align=button.dataset.imageAlign;selectedImage.style.marginLeft=align==='left'?'0':align==='center'?'auto':'auto';selectedImage.style.marginRight=align==='right'?'0':align==='center'?'auto':'auto';queueAutoSave()}));document.querySelector('#deleteImageButton').addEventListener('click',()=>{selectedImage?.remove();selectedImage=null;document.querySelector('#imageToolbar').classList.add('hidden');queueAutoSave();updateStats()});
document.querySelector('#tableButton').addEventListener('click',()=>{rememberSelection();const rows=Math.min(15,Math.max(1,Number(prompt('Сколько строк?',3))||0));if(!rows)return;const columns=Math.min(10,Math.max(1,Number(prompt('Сколько столбцов?',3))||0));if(!columns)return;let html='<table><tbody>';for(let r=0;r<rows;r++){html+='<tr>';for(let c=0;c<columns;c++)html+=`<${r===0?'th':'td'}>${r===0?'Заголовок':'Текст'}</${r===0?'th':'td'}>`;html+='</tr>'}html+='</tbody></table><p><br></p>';restoreSelection();document.execCommand('insertHTML',false,html);queueAutoSave();showToast('Таблица вставлена')});
document.querySelector('#tableEditButton').addEventListener('click',()=>document.querySelector('#tableMenuPanel').classList.toggle('hidden'));document.querySelectorAll('[data-table-action]').forEach(button=>button.addEventListener('click',()=>{if(!activeTableCell){showToast('Сначала нажмите на ячейку таблицы');return}const row=activeTableCell.parentElement,table=activeTableCell.closest('table'),index=[...row.cells].indexOf(activeTableCell),action=button.dataset.tableAction;if(action==='row-after'){const clone=row.cloneNode(true);[...clone.cells].forEach(cell=>cell.innerText='Текст');row.after(clone)}else if(action==='column-after'){[...table.rows].forEach((tr,r)=>{const cell=tr.insertCell(Math.min(index+1,tr.cells.length));cell.outerHTML=r===0?'<th>Заголовок</th>':'<td>Текст</td>'})}else if(action==='delete-row'){row.remove()}else if(action==='delete-column'){[...table.rows].forEach(tr=>tr.cells[index]?.remove())}else if(action==='delete-table'){table.remove()}if(!table.rows.length||!table.rows[0]?.cells.length)table.remove();document.querySelector('#tableMenuPanel').classList.add('hidden');queueAutoSave();updateStats()}));
document.querySelector('#linkButton').addEventListener('click',()=>{rememberSelection();const url=prompt('Введите адрес ссылки, например https://example.com');if(!url)return;restoreSelection();document.execCommand('createLink',false,url);queueAutoSave()});
document.querySelector('#dateButton').addEventListener('click',()=>{restoreSelection();document.execCommand('insertText',false,new Date().toLocaleDateString('ru-RU'));queueAutoSave()});
document.querySelector('#pageBreakButton').addEventListener('click',()=>{restoreSelection();document.execCommand('insertHTML',false,'<div class="page-break" contenteditable="false"></div><p><br></p>');queueAutoSave();updateStats()});
document.querySelector('#quoteButton').addEventListener('click',()=>{restoreSelection();document.execCommand('formatBlock',false,'blockquote');queueAutoSave();showToast('Блок цитаты добавлен')});
document.querySelector('#codeButton').addEventListener('click',()=>{restoreSelection();const selected=window.getSelection().toString()||'Введите код здесь';document.execCommand('insertHTML',false,`<pre>${escapeHtml(selected)}</pre><p><br></p>`);queueAutoSave();updateStats()});
document.querySelector('#checklistButton').addEventListener('click',()=>{restoreSelection();document.execCommand('insertHTML',false,'<div class="check-item"><input type="checkbox" contenteditable="false"><span>Новая задача</span></div><p><br></p>');queueAutoSave();updateStats()});
document.querySelector('#tocButton').addEventListener('click',()=>{const headings=[...editor.querySelectorAll('h1,h2,h3')].filter(item=>!item.closest('.document-toc'));if(!headings.length){showToast('Сначала добавьте заголовки');return}headings.forEach((heading,index)=>heading.id=`toc-heading-${index}`);const links=headings.map(heading=>`<a class="toc-level-${heading.tagName.slice(1)}" href="#${heading.id}">${escapeHtml(heading.innerText)}</a>`).join('');const old=editor.querySelector('.document-toc');old?.remove();editor.insertAdjacentHTML('afterbegin',`<nav class="document-toc" contenteditable="false"><strong>Оглавление</strong>${links}</nav><p><br></p>`);queueAutoSave();updateStats();showToast('Оглавление создано')});
document.querySelector('#signatureButton').addEventListener('click',()=>{restoreSelection();document.execCommand('insertHTML',false,'<div class="signature-line">Подпись: ____________________ &nbsp; Дата: __________</div><p><br></p>');queueAutoSave();updateStats()});
document.querySelector('#plainPasteButton').addEventListener('click',async()=>{let text='';try{text=await navigator.clipboard.readText()}catch{text=prompt('Вставьте текст без форматирования:')||''}if(!text)return;restoreSelection();document.execCommand('insertText',false,text);queueAutoSave();updateStats();showToast('Текст вставлен без форматирования')});
document.querySelector('#horizontalRuleButton').addEventListener('click',()=>{restoreSelection();document.execCommand('insertHTML',false,'<hr><p><br></p>');queueAutoSave();updateStats()});
document.querySelector('#calloutSelect').addEventListener('change',event=>{const type=event.target.value;if(!type)return;const labels={info:'ℹ Информация',tip:'💡 Полезный совет',warning:'⚠ Важная информация'};restoreSelection();document.execCommand('insertHTML',false,`<div class="callout callout-${type}"><strong>${labels[type]}</strong><p>Введите текст блока.</p></div><p><br></p>`);event.target.value='';queueAutoSave();updateStats()});
const quickBlocks={meeting:'<h2>Протокол встречи</h2><p><b>Дата:</b> __________ &nbsp; <b>Участники:</b> __________</p><h3>Повестка</h3><ol><li>Вопрос встречи</li></ol><h3>Решения</h3><ul><li>Принятое решение и ответственный</li></ul>',notice:'<h2>Служебная записка</h2><p><b>Кому:</b> __________<br><b>От кого:</b> __________<br><b>Дата:</b> __________</p><p><b>Тема:</b> __________</p><p>Введите текст служебной записки.</p>',approval:'<div class="approval-block"><div><b>Подготовил</b><br><br>____________ / Ф.И.О.<br>Дата: __________</div><div><b>Согласовано</b><br><br>____________ / Ф.И.О.<br>Дата: __________</div></div><p><br></p>'};
document.querySelector('#quickBlockSelect').addEventListener('change',event=>{const html=quickBlocks[event.target.value];if(!html)return;restoreSelection();document.execCommand('insertHTML',false,html);event.target.value='';queueAutoSave();updateStats();updateOutline();showToast('Готовый блок вставлен')});
document.querySelector('#findButton').addEventListener('click',()=>{const find=prompt('Какой текст найти?');if(!find)return;const replacement=prompt('На какой текст заменить? Оставьте пустым, чтобы удалить.',find);if(replacement===null)return;const walker=document.createTreeWalker(editor,NodeFilter.SHOW_TEXT);let count=0,node;const expression=new RegExp(escapeRegExp(find),'gi');while(node=walker.nextNode()){if(expression.test(node.nodeValue)){node.nodeValue=node.nodeValue.replace(expression,()=>{count++;return replacement})}expression.lastIndex=0}updateStats();queueAutoSave();showToast(count?`Заменено: ${count}`:'Текст не найден')});
document.querySelector('#marginSelect').addEventListener('change',event=>{editor.classList.remove('margins-narrow','margins-wide');if(event.target.value!=='normal')editor.classList.add(`margins-${event.target.value}`);queueAutoSave()});
document.querySelector('#orientationSelect').addEventListener('change',event=>{editor.classList.toggle('orientation-landscape',event.target.value==='landscape');queueAutoSave();updateStats()});
document.querySelector('#pageSizeSelect').addEventListener('change',event=>{applyPageSize(event.target.value);queueAutoSave();updateStats()});function applyPageSize(size='a4'){document.querySelector('#pageSizeSelect').value=size;editor.classList.remove('size-a5','size-letter');if(size!=='a4')editor.classList.add(`size-${size}`)}
document.querySelector('#pageColor').addEventListener('input',event=>{editor.style.backgroundColor=event.target.value;queueAutoSave()});
document.querySelector('#columnsSelect').addEventListener('change',event=>{applyColumns(event.target.value);queueAutoSave();updateStats()});
function applyColumns(value=1){document.querySelector('#columnsSelect').value=String(value);editor.classList.toggle('two-columns',String(value)==='2')}
document.querySelector('#spellButton').addEventListener('click',event=>{editor.spellcheck=!editor.spellcheck;event.currentTarget.classList.toggle('active-tool',editor.spellcheck);event.currentTarget.textContent=editor.spellcheck?'✓ Орфография':'× Орфография';editor.focus()});
document.querySelector('#readingModeButton').addEventListener('click',event=>{const reading=document.body.classList.toggle('reading-mode');editor.contentEditable=String(!reading);event.currentTarget.textContent=reading?'✏️ Редактировать':'👁 Чтение';showToast(reading?'Режим чтения включён':'Редактирование включено')});
document.querySelector('#commentButton').addEventListener('click',()=>{const selection=window.getSelection();if(selection.isCollapsed||!editor.contains(selection.anchorNode)){showToast('Сначала выделите текст');return}const comment=prompt('Введите комментарий:');if(!comment)return;const selected=selection.toString();document.execCommand('insertHTML',false,`<span class="comment-mark" data-comment="${escapeHtml(comment)}">${escapeHtml(selected)}</span>`);queueAutoSave();renderComments();showToast('Комментарий добавлен')});
document.querySelector('#commentsButton').addEventListener('click',()=>{renderComments();document.querySelector('#commentsPanel').classList.toggle('hidden')});document.querySelector('#closeCommentsButton').addEventListener('click',()=>document.querySelector('#commentsPanel').classList.add('hidden'));
function renderComments(){const list=document.querySelector('#commentsList'),marks=[...editor.querySelectorAll('.comment-mark')];list.innerHTML=marks.length?'':'<div class="history-empty">Комментариев пока нет.</div>';marks.forEach((mark,index)=>{mark.dataset.commentId=index;const item=document.createElement('div');item.className='comment-item';item.innerHTML=`<strong>«${escapeHtml(mark.innerText.slice(0,45))}»</strong><span>${escapeHtml(mark.dataset.comment||'')}</span><button data-comment-go="${index}">Показать</button> <button data-comment-delete="${index}">Удалить</button>`;list.append(item)});list.querySelectorAll('[data-comment-go]').forEach(button=>button.onclick=()=>editor.querySelector(`[data-comment-id="${button.dataset.commentGo}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}));list.querySelectorAll('[data-comment-delete]').forEach(button=>button.onclick=()=>{const mark=editor.querySelector(`[data-comment-id="${button.dataset.commentDelete}"]`);if(mark)mark.replaceWith(document.createTextNode(mark.innerText));renderComments();queueAutoSave()})}
document.querySelector('#addBookmarkButton').addEventListener('click',()=>{const name=prompt('Название закладки:','Важное место');if(!name)return;restoreSelection();const selection=window.getSelection(),id=`bookmark-${Date.now()}`;if(selection&&!selection.isCollapsed&&editor.contains(selection.anchorNode))document.execCommand('insertHTML',false,`<span id="${id}" class="document-bookmark" data-bookmark="${escapeHtml(name)}">${escapeHtml(selection.toString())}</span>`);else document.execCommand('insertHTML',false,`<span id="${id}" class="document-bookmark" data-bookmark="${escapeHtml(name)}">🔖 ${escapeHtml(name)}</span>`);queueAutoSave();renderBookmarks();showToast('Закладка добавлена')});document.querySelector('#bookmarksButton').addEventListener('click',()=>{renderBookmarks();document.querySelector('#bookmarksPanel').classList.toggle('hidden')});document.querySelector('#closeBookmarksButton').addEventListener('click',()=>document.querySelector('#bookmarksPanel').classList.add('hidden'));
function renderBookmarks(){const list=document.querySelector('#bookmarksList'),marks=[...editor.querySelectorAll('.document-bookmark')];list.innerHTML=marks.length?'':'<div class="history-empty">Закладок пока нет.</div>';marks.forEach((mark,index)=>{mark.dataset.bookmarkIndex=index;const item=document.createElement('div');item.className='comment-item';item.innerHTML=`<strong>${escapeHtml(mark.dataset.bookmark||`Закладка ${index+1}`)}</strong><span>${escapeHtml(mark.innerText.slice(0,55))}</span><button data-bookmark-go="${index}">Перейти</button> <button data-bookmark-delete="${index}">Удалить</button>`;list.append(item)});list.querySelectorAll('[data-bookmark-go]').forEach(button=>button.onclick=()=>editor.querySelector(`[data-bookmark-index="${button.dataset.bookmarkGo}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}));list.querySelectorAll('[data-bookmark-delete]').forEach(button=>button.onclick=()=>{const mark=editor.querySelector(`[data-bookmark-index="${button.dataset.bookmarkDelete}"]`);mark?.replaceWith(document.createTextNode(mark.innerText));renderBookmarks();queueAutoSave()})}
document.querySelector('#watermarkButton').addEventListener('click',()=>{const text=prompt('Введите водяной знак. Оставьте пустым, чтобы удалить:',editor.dataset.watermark||'ЧЕРНОВИК');if(text===null)return;if(text.trim())editor.dataset.watermark=text.trim();else delete editor.dataset.watermark;queueAutoSave()});document.querySelector('#borderButton').addEventListener('click',()=>{editor.classList.toggle('page-border');queueAutoSave()});
document.querySelector('#statsButton').addEventListener('click',()=>{showDocumentStats();document.querySelector('#statsModal').classList.remove('hidden')});document.querySelector('#closeStatsButton').addEventListener('click',()=>document.querySelector('#statsModal').classList.add('hidden'));document.querySelector('#statsModal').addEventListener('click',event=>{if(event.target.id==='statsModal')event.currentTarget.classList.add('hidden')});
function showDocumentStats(){document.querySelector('#statsModalTitle').textContent='Статистика документа';document.querySelector('#statsGrid').classList.remove('hidden');document.querySelector('#frequencyList').classList.add('hidden');const text=getPlainText(),words=text?text.split(/\s+/).length:0,sentences=(text.match(/[.!?]+(?=\s|$)/g)||[]).length,paragraphs=[...editor.querySelectorAll('p,h1,h2,h3,li')].filter(x=>x.innerText.trim()).length,images=editor.querySelectorAll('img').length,tables=editor.querySelectorAll('table').length,pages=Math.max(1,Math.ceil(editor.scrollHeight/1123));const items=[['Слов',words],['Знаков',text.length],['Предложений',sentences],['Абзацев',paragraphs],['Страниц',pages],['Время чтения',words<180?'< 1 мин':Math.ceil(words/180)+' мин'],['Изображений',images],['Таблиц',tables],['Комментариев',editor.querySelectorAll('.comment-mark').length]];document.querySelector('#statsGrid').innerHTML=items.map(([label,value])=>`<div class="stat-box"><strong>${value}</strong><span>${label}</span></div>`).join('')}
document.querySelector('#frequencyButton').addEventListener('click',()=>{const stop=new Set(['и','в','во','на','с','со','а','но','это','как','к','по','из','за','для','не','что','я','мы','вы','он','она','они']),words=(getPlainText().toLowerCase().match(/[а-яёa-z]{3,}/gi)||[]).filter(word=>!stop.has(word)),counts={};words.forEach(word=>counts[word]=(counts[word]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,12),max=top[0]?.[1]||1,list=document.querySelector('#frequencyList');document.querySelector('#statsModalTitle').textContent='Часто повторяющиеся слова';document.querySelector('#statsGrid').classList.add('hidden');list.classList.remove('hidden');list.innerHTML=top.length?top.map(([word,count])=>`<div class="frequency-row"><strong>${escapeHtml(word)}</strong><i style="width:${count/max*100}%"></i><span>${count}×</span></div>`).join(''):'<div class="history-empty">Недостаточно текста для анализа</div>';document.querySelector('#statsModal').classList.remove('hidden')});
document.querySelector('#accessibilityButton').addEventListener('click',()=>{const issues=[],images=[...editor.querySelectorAll('img')].filter(img=>!img.alt),emptyLinks=[...editor.querySelectorAll('a')].filter(link=>!link.innerText.trim()),longParagraphs=[...editor.querySelectorAll('p')].filter(p=>p.innerText.length>500),tables=[...editor.querySelectorAll('table')].filter(table=>!table.querySelector('th'));if(!editor.querySelector('h1'))issues.push('Добавьте главный заголовок H1');if(images.length)issues.push(`Изображения без описания: ${images.length}`);if(emptyLinks.length)issues.push(`Ссылки без понятного текста: ${emptyLinks.length}`);if(longParagraphs.length)issues.push(`Слишком длинные абзацы: ${longParagraphs.length}`);if(tables.length)issues.push(`Таблицы без строки заголовков: ${tables.length}`);const result=document.querySelector('#accessibilityResults');result.innerHTML=issues.length?issues.map(text=>`<div class="accessibility-item warn">⚠ ${escapeHtml(text)}</div>`).join(''):'<div class="accessibility-item good">✓ Основных проблем доступности не найдено</div>';document.querySelector('#accessibilityModal').classList.remove('hidden')});document.querySelector('#closeAccessibilityButton').addEventListener('click',()=>document.querySelector('#accessibilityModal').classList.add('hidden'));
document.querySelector('#languageSelect').addEventListener('change',event=>{editor.lang=event.target.value;editor.spellcheck=true;document.querySelector('#spellButton').classList.add('active-tool');queueAutoSave();showToast(`Язык проверки: ${event.target.options[event.target.selectedIndex].text}`)});
document.querySelector('#propertiesButton').addEventListener('click',()=>{document.querySelector('#documentAuthor').value=documentMeta.author||'';document.querySelector('#documentSubject').value=documentMeta.subject||'';document.querySelector('#documentKeywords').value=documentMeta.keywords||'';document.querySelector('#propertiesModal').classList.remove('hidden')});document.querySelector('#closePropertiesButton').addEventListener('click',()=>document.querySelector('#propertiesModal').classList.add('hidden'));document.querySelector('#savePropertiesButton').addEventListener('click',()=>{documentMeta={author:document.querySelector('#documentAuthor').value.trim(),subject:document.querySelector('#documentSubject').value.trim(),keywords:document.querySelector('#documentKeywords').value.trim()};document.querySelector('#propertiesModal').classList.add('hidden');queueAutoSave();showToast('Свойства документа сохранены')});
document.querySelector('#caseSelect').addEventListener('change',event=>{const mode=event.target.value,selection=window.getSelection();if(!mode||selection.isCollapsed||!editor.contains(selection.anchorNode)){showToast('Сначала выделите текст');event.target.value='';return}const original=selection.toString();let changed=original;if(mode==='upper')changed=original.toUpperCase();if(mode==='lower')changed=original.toLowerCase();if(mode==='sentence')changed=original.toLowerCase().replace(/(^|[.!?]\s+)\p{L}/gu,match=>match.toUpperCase());if(mode==='title')changed=original.toLowerCase().replace(/(^|\s)\p{L}/gu,match=>match.toUpperCase());document.execCommand('insertText',false,changed);event.target.value='';queueAutoSave();updateStats()});
document.querySelector('#cleanSpacesButton').addEventListener('click',()=>{if(!confirm('Убрать повторяющиеся пробелы во всём документе?'))return;const walker=document.createTreeWalker(editor,NodeFilter.SHOW_TEXT);let node,count=0;while(node=walker.nextNode()){const cleaned=node.nodeValue.replace(/[ \t]{2,}/g,' ').replace(/ +([,.;:!?])/g,'$1');if(cleaned!==node.nodeValue){node.nodeValue=cleaned;count++}}queueAutoSave();updateStats();showToast(`Исправлено фрагментов: ${count}`)});
document.querySelector('#copyFormatButton').addEventListener('click',event=>{const selection=window.getSelection(),node=selection.anchorNode?.nodeType===3?selection.anchorNode.parentElement:selection.anchorNode;if(!node||!editor.contains(node)){showToast('Сначала выберите оформленный текст');return}const style=getComputedStyle(node);copiedTextStyle=`font-family:${style.fontFamily};font-size:${style.fontSize};font-weight:${style.fontWeight};font-style:${style.fontStyle};text-decoration:${style.textDecoration};color:${style.color};background-color:${style.backgroundColor}`;event.currentTarget.classList.add('format-ready');showToast('Оформление скопировано')});
document.querySelector('#applyFormatButton').addEventListener('click',()=>{const selection=window.getSelection();if(!copiedTextStyle){showToast('Сначала скопируйте оформление');return}if(selection.isCollapsed||!editor.contains(selection.anchorNode)){showToast('Выделите текст для оформления');return}document.execCommand('insertHTML',false,`<span style="${copiedTextStyle}">${escapeHtml(selection.toString())}</span>`);queueAutoSave();updateStats();showToast('Оформление применено')});
document.querySelector('#trackChangesButton').addEventListener('click',event=>{trackChanges=!trackChanges;event.currentTarget.classList.toggle('active-tool',trackChanges);event.currentTarget.textContent=trackChanges?'🟢 Исправления включены':'📝 Исправления';showToast(trackChanges?'Новый текст будет отмечаться':'Режим исправлений выключен')});
document.querySelector('#acceptChangesButton').addEventListener('click',()=>{const changes=[...editor.querySelectorAll('.tracked-insert')];changes.forEach(mark=>mark.replaceWith(document.createTextNode(mark.textContent)));queueAutoSave();updateStats();showToast(`Принято изменений: ${changes.length}`)});
document.querySelector('#rejectChangesButton').addEventListener('click',()=>{const changes=[...editor.querySelectorAll('.tracked-insert')];if(changes.length&&!confirm('Удалить все отмеченные добавления?'))return;changes.forEach(mark=>mark.remove());queueAutoSave();updateStats();showToast(`Отклонено изменений: ${changes.length}`)});
document.querySelector('#wordGoalButton').addEventListener('click',()=>{const value=prompt('Сколько слов вы хотите написать? Введите 0, чтобы убрать цель:',wordGoal||500);if(value===null)return;wordGoal=Math.max(0,Math.round(Number(value)||0));localStorage.setItem('myword2026-word-goal',String(wordGoal));updateStats();queueAutoSave();showToast(wordGoal?`Цель установлена: ${wordGoal} слов`:'Цель удалена')});
document.querySelector('#symbolsButton').addEventListener('click',()=>document.querySelector('#symbolsPanel').classList.toggle('hidden'));
document.querySelectorAll('#symbolsPanel button').forEach(button=>button.addEventListener('click',()=>{restoreSelection();document.execCommand('insertText',false,button.textContent);document.querySelector('#symbolsPanel').classList.add('hidden');queueAutoSave();updateStats()}));
document.querySelector('#headerButton').addEventListener('click',()=>{let header=editor.querySelector('.document-header');const current=header?.innerText||'';const text=prompt('Введите текст верхнего колонтитула:',current);if(text===null)return;if(!header){header=document.createElement('div');header.className='document-header';editor.prepend(header)}header.innerText=text;queueAutoSave();updateStats()});
document.querySelector('#footerButton').addEventListener('click',()=>{let footer=editor.querySelector('.document-footer');if(footer){footer.remove();showToast('Номер страницы удалён')}else{footer=document.createElement('div');footer.className='document-footer';footer.innerHTML='Страница <span class="dynamic-page-number">1</span>';editor.append(footer);showToast('Номер страницы добавлен')}queueAutoSave();updateStats()});
document.querySelector('#outlineButton').addEventListener('click',()=>{document.querySelector('#outlinePanel').classList.toggle('hidden');updateOutline()});document.querySelector('#closeOutlineButton').addEventListener('click',()=>document.querySelector('#outlinePanel').classList.add('hidden'));
function updateOutline(){const list=document.querySelector('#outlineList'),headings=[...editor.querySelectorAll('h1,h2,h3')];if(!headings.length){list.innerHTML='<p>Добавьте заголовки в документ.</p>';return}list.innerHTML='';headings.forEach((heading,index)=>{heading.id=`heading-${index}`;const button=document.createElement('button');button.className=`level-${heading.tagName.slice(1)}`;button.textContent=heading.innerText||'Без названия';button.onclick=()=>heading.scrollIntoView({behavior:'smooth',block:'center'});list.append(button)})}
document.querySelector('#lineHeight').addEventListener('change',event=>{restoreSelection();document.execCommand('formatBlock',false,'div');const selection=window.getSelection();let element=selection.anchorNode?.nodeType===3?selection.anchorNode.parentElement:selection.anchorNode;if(element&&editor.contains(element)){element.style.lineHeight=event.target.value;queueAutoSave()}});
const ribbonGroups={home:['.history-tools','.font-tools','.paragraph-tools','.style-tools'],insert:['.insert-tools'],design:['.style-tools','.document-tools'],layout:['.document-tools'],links:['.insert-tools','.document-tools'],mail:['.insert-tools'],review:['.document-tools'],view:['.document-tools']};
function showRibbon(name='home'){document.querySelectorAll('.ribbon>.tool-group').forEach(group=>group.style.display='none');(ribbonGroups[name]||ribbonGroups.home).forEach(selector=>{const group=document.querySelector(selector);if(group)group.style.display='flex'})}
document.querySelectorAll('.tab[data-ribbon]').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');showRibbon(tab.dataset.ribbon)}));
document.querySelectorAll('[data-word-style]').forEach(button=>button.addEventListener('click',()=>{runCommand('formatBlock',button.dataset.wordStyle);document.querySelector('#blockFormat').value=['p','h1','h2','h3'].includes(button.dataset.wordStyle)?button.dataset.wordStyle:'p'}));
const fileMenu=document.querySelector('#fileMenu'),fileMenuButton=document.querySelector('#fileMenuButton');fileMenuButton.addEventListener('click',event=>{event.stopPropagation();fileMenu.classList.toggle('hidden');fileMenuButton.classList.toggle('open',!fileMenu.classList.contains('hidden'))});document.querySelectorAll('[data-file-action]').forEach(button=>button.addEventListener('click',()=>{fileMenu.classList.add('hidden');fileMenuButton.classList.remove('open');document.querySelector(`#${button.dataset.fileAction}`)?.click()}));document.addEventListener('click',event=>{if(!fileMenu.contains(event.target)&&event.target!==fileMenuButton){fileMenu.classList.add('hidden');fileMenuButton.classList.remove('open')}});
document.querySelectorAll('[data-mac-command]').forEach(button=>button.addEventListener('click',()=>{const map={edit:'home',view:'view',insert:'insert',format:'home',tools:'review',table:'insert',window:'view'};const target=map[button.dataset.macCommand];if(target){document.querySelector(`.tab[data-ribbon="${target}"]`)?.click()}else showToast('Раздел «Справка» добавим позже')}));
function updateMenuClock(){document.querySelector('#menuClock').textContent=new Date().toLocaleString('ru-RU',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}updateMenuClock();setInterval(updateMenuClock,30000);
const quickCommands=[['📄','Новый документ','Создать пустой документ','newButton'],['▦','Шаблоны','Открыть галерею шаблонов','templatesButton'],['📂','Открыть файл','HTML, TXT или проект MyWord','openButton'],['💾','Сохранить проект','Сохранить все настройки','projectButton'],['🔒','Защитить паролем','Создать зашифрованный файл','lockedButton'],['🖨️','Печать или PDF','Открыть окно печати','printButton'],['🔎','Найти и заменить','Поиск по документу','findButton'],['🖼','Вставить изображение','Добавить фотографию','imageButton'],['▦','Вставить таблицу','Создать таблицу','tableButton'],['☑','Добавить чек-лист','Список задач с флажками','checklistButton'],['☷','Создать оглавление','Собрать заголовки документа','tocButton'],['🌙','Сменить тему','Светлый или тёмный режим','themeButton'],['📊','Статистика','Подробный анализ документа','statsButton'],['👁','Режим чтения','Скрыть инструменты редактора','readingModeButton']];
function openCommandPalette(){document.querySelector('#commandModal').classList.remove('hidden');const input=document.querySelector('#commandSearch');input.value='';renderCommands('');setTimeout(()=>input.focus(),30)}
function renderCommands(query=''){const list=document.querySelector('#commandList'),term=query.trim().toLowerCase(),items=quickCommands.filter(item=>(item[1]+' '+item[2]).toLowerCase().includes(term));list.innerHTML=items.length?'':'<div class="history-empty">Команда не найдена</div>';items.forEach(([icon,name,description,id])=>{const button=document.createElement('button');button.className='command-item';button.innerHTML=`<b>${icon}</b><div><strong>${name}</strong><span>${description}</span></div>`;button.onclick=()=>{document.querySelector('#commandModal').classList.add('hidden');document.querySelector(`#${id}`)?.click()};list.append(button)})}
document.querySelector('#commandButton').addEventListener('click',openCommandPalette);document.querySelector('#closeCommandButton').addEventListener('click',()=>document.querySelector('#commandModal').classList.add('hidden'));document.querySelector('#commandSearch').addEventListener('input',event=>renderCommands(event.target.value));document.querySelector('#commandModal').addEventListener('click',event=>{if(event.target.id==='commandModal')event.currentTarget.classList.add('hidden')});
document.addEventListener('selectionchange',()=>{const selection=window.getSelection(),text=selection&&editor.contains(selection.anchorNode)?selection.toString().trim():'';const words=text?text.split(/\s+/).length:0;document.querySelector('#selectionCount').textContent=text?`Выделено: ${words} сл. · ${text.length} зн.`:'Выделено: 0'});editor.addEventListener('change',event=>{if(event.target.matches('.check-item input'))queueAutoSave()});
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelector('#commandModal').classList.add('hidden');if(!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key==='k'){event.preventDefault();openCommandPalette()}else if(key==='w'&&event.shiftKey){event.preventDefault();document.querySelector('#docButton').click()}else if(key==='s'){event.preventDefault();document.querySelector('#projectButton').click()}else if(key==='f'){event.preventDefault();document.querySelector('#findButton').click()}else if(key==='p'){event.preventDefault();window.print()}else if(key==='b'){event.preventDefault();runCommand('bold')}else if(key==='i'){event.preventDefault();runCommand('italic')}else if(key==='u'){event.preventDefault();runCommand('underline')}});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='ru-RU';recognition.continuous=true;recognition.interimResults=false;recognition.onresult=event=>{restoreSelection();for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)document.execCommand('insertText',false,event.results[i][0].transcript+' ');updateStats();queueAutoSave()};recognition.onend=()=>document.querySelector('#voiceButton').classList.remove('voice-active')}document.querySelector('#voiceButton').addEventListener('click',()=>{if(!recognition){showToast('Голосовой ввод не поддерживается этим браузером');return}rememberSelection();const button=document.querySelector('#voiceButton');if(button.classList.contains('voice-active')){recognition.stop();button.classList.remove('voice-active')}else{recognition.start();button.classList.add('voice-active');showToast('Говорите — текст будет добавлен')}});

function downloadFile(content,name,type){const blob=new Blob([content],{type:`${type};charset=utf-8`});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)}
function safeName(name){return(name.trim()||'document').replace(/[\\/:*?"<>|]/g,'-')}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function escapeRegExp(value){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function editorToMarkdown(){function convert(node,depth=0){if(node.nodeType===Node.TEXT_NODE)return node.nodeValue;if(node.nodeType!==Node.ELEMENT_NODE)return'';const tag=node.tagName.toLowerCase(),inside=[...node.childNodes].map(child=>convert(child,depth)).join('');if(tag==='h1'||tag==='h2'||tag==='h3')return`${'#'.repeat(Number(tag[1]))} ${inside.trim()}\n\n`;if(tag==='p'||tag==='div')return`${inside.trim()}\n\n`;if(tag==='br')return'\n';if(tag==='strong'||tag==='b')return`**${inside}**`;if(tag==='em'||tag==='i')return`*${inside}*`;if(tag==='s')return`~~${inside}~~`;if(tag==='a')return`[${inside}](${node.getAttribute('href')||''})`;if(tag==='blockquote')return inside.trim().split('\n').map(line=>`> ${line}`).join('\n')+'\n\n';if(tag==='pre')return`\`\`\`\n${node.innerText}\n\`\`\`\n\n`;if(tag==='li')return`${node.parentElement.tagName==='OL'?`${[...node.parentElement.children].indexOf(node)+1}.`:'-'} ${inside.trim()}\n`;if(tag==='ul'||tag==='ol')return inside+'\n';if(tag==='img')return`![изображение](${node.getAttribute('src')||''})`;if(tag==='hr')return'---\n\n';if(node.classList.contains('check-item'))return`- [${node.querySelector('input')?.checked?'x':' '}] ${node.innerText.trim()}\n`;if(node.classList.contains('document-toc'))return'';return inside}return[...editor.childNodes].map(node=>convert(node)).join('').replace(/\n{3,}/g,'\n\n').trim()+'\n'}
function applyPageSettings(margins='normal',orientation='portrait',pageColor='#ffffff'){document.querySelector('#marginSelect').value=margins;document.querySelector('#orientationSelect').value=orientation;document.querySelector('#pageColor').value=pageColor;editor.style.backgroundColor=pageColor;editor.classList.remove('margins-narrow','margins-wide','orientation-landscape');if(margins!=='normal')editor.classList.add(`margins-${margins}`);if(orientation==='landscape')editor.classList.add('orientation-landscape')}
// Помощник 2026 и быстрые команды версии 15
const assistantPanel=document.querySelector('#assistantPanel'),assistantResult=document.querySelector('#assistantResult'),slashMenu=document.querySelector('#slashMenu');let assistantText='';
function openAssistant(){rememberSelection();assistantPanel.classList.remove('hidden');document.querySelector('#assistantButton').classList.add('active')}
function closeAssistant(){assistantPanel.classList.add('hidden');document.querySelector('#assistantButton').classList.remove('active')}
function assistantSource(){const selection=savedRange?.toString().trim();return selection||getPlainText()}
function tidyText(text){return text.replace(/[ \t]+/g,' ').replace(/\s+([,.;:!?])/g,'$1').replace(/([.!?])(?=\p{L})/gu,'$1 ').replace(/\n{3,}/g,'\n\n').trim()}
function setAssistantResult(text){assistantText=text;assistantResult.textContent=text||'Не удалось создать результат'}
function shortSummary(text){const sentences=(tidyText(text).match(/[^.!?\n]+[.!?]?/g)||[]).map(x=>x.trim()).filter(x=>x.length>20);if(!sentences.length)return tidyText(text);const wanted=Math.min(4,Math.max(2,Math.ceil(sentences.length*.3)));return sentences.slice(0,wanted).map(x=>`• ${x}`).join('\n')}
function formalize(text){return tidyText(text).replace(/\bпривет\b/gi,'Здравствуйте').replace(/\bхочу\b/gi,'планирую').replace(/\bнадо\b/gi,'необходимо').replace(/\bможно\b/gi,'возможно').replace(/\bок\b/gi,'Согласовано')}
document.querySelector('#assistantButton').addEventListener('click',()=>assistantPanel.classList.contains('hidden')?openAssistant():closeAssistant());document.querySelector('#closeAssistantButton').addEventListener('click',closeAssistant);
document.querySelectorAll('[data-assistant]').forEach(button=>button.addEventListener('click',()=>{const source=assistantSource();if(!source){showToast('Добавьте или выделите текст');return}const action=button.dataset.assistant;if(action==='improve')setAssistantResult(tidyText(source));if(action==='summary')setAssistantResult(shortSummary(source));if(action==='formal')setAssistantResult(formalize(source));if(action==='tasks'){const lines=tidyText(source).split(/\n|[.!?]+/).map(x=>x.trim()).filter(x=>x.length>8).slice(0,7);setAssistantResult(lines.map(x=>`☐ ${x}`).join('\n'))}}));
document.querySelector('#assistantInsertButton').addEventListener('click',()=>{const idea=document.querySelector('#assistantPrompt').value.trim();if(!idea){showToast('Введите тему блока');return}setAssistantResult(`${idea}\n\nЦель: ____________________\nКлючевые пункты:\n• ____________________\n• ____________________\nСледующий шаг: ____________________`)});
document.querySelector('#copyAssistantResultButton').addEventListener('click',async()=>{if(!assistantText)return;try{await navigator.clipboard.writeText(assistantText);showToast('Результат скопирован')}catch{showToast('Копирование недоступно')}});document.querySelector('#insertAssistantResultButton').addEventListener('click',()=>{if(!assistantText)return;restoreSelection();document.execCommand('insertHTML',false,`<div class="assistant-inserted">${escapeHtml(assistantText).replace(/\n/g,'<br>')}</div>`);queueAutoSave();updateStats();showToast('Результат вставлен')});
document.querySelector('#compactRibbonButton').addEventListener('click',event=>{document.body.classList.toggle('ribbon-collapsed');const compact=document.body.classList.contains('ribbon-collapsed');event.currentTarget.textContent=compact?'⌄ Лента':'⌃ Лента';localStorage.setItem('myword2026-ribbon',compact?'collapsed':'open')});if(localStorage.getItem('myword2026-ribbon')==='collapsed'){document.body.classList.add('ribbon-collapsed');document.querySelector('#compactRibbonButton').textContent='⌄ Лента'}
document.querySelector('#quickShareButton').addEventListener('click',async()=>{const shareText=`${titleInput.value}\n\n${getPlainText()}`;if(navigator.share){try{await navigator.share({title:titleInput.value,text:shareText});return}catch{}}try{await navigator.clipboard.writeText(shareText);showToast('Документ скопирован для отправки')}catch{showToast('Не удалось скопировать документ')}});
editor.addEventListener('keyup',event=>{if(event.key!=='/')return;const range=window.getSelection()?.getRangeAt(0);if(!range)return;const rect=range.getBoundingClientRect();slashMenu.style.left=`${Math.min(innerWidth-260,Math.max(8,rect.left))}px`;slashMenu.style.top=`${Math.min(innerHeight-270,Math.max(110,rect.bottom+8))}px`;slashMenu.classList.remove('hidden')});
document.querySelectorAll('[data-slash]').forEach(button=>button.addEventListener('mousedown',event=>{event.preventDefault();restoreSelection();document.execCommand('delete');const action=button.dataset.slash;if(action==='h1')document.execCommand('formatBlock',false,'h1');if(action==='check')document.querySelector('#checklistButton').click();if(action==='quote')document.querySelector('#quoteButton').click();if(action==='table')document.querySelector('#tableButton').click();if(action==='date')document.querySelector('#dateButton').click();if(action==='assistant')openAssistant();slashMenu.classList.add('hidden');queueAutoSave()}));document.addEventListener('mousedown',event=>{if(!slashMenu.contains(event.target))slashMenu.classList.add('hidden')});
function applyDocumentExtras(data={}){if(data.watermark)editor.dataset.watermark=data.watermark;else delete editor.dataset.watermark;editor.classList.toggle('page-border',Boolean(data.pageBorder))}
function loadDocumentData(data){titleInput.value=data.title||'Документ';document.querySelector('.window-title').textContent=titleInput.value;editor.innerHTML=data.html||'';documentMeta=data.meta||{author:'',subject:'',keywords:''};editor.lang=data.language||'ru-RU';document.querySelector('#languageSelect').value=editor.lang;if(Number.isFinite(Number(data.wordGoal))){wordGoal=Math.max(0,Number(data.wordGoal));localStorage.setItem('myword2026-word-goal',String(wordGoal))}applyPageSettings(data.margins||'normal',data.orientation||'portrait',data.pageColor||'#ffffff');applyPageSize(data.pageSize||'a4');applyColumns(data.columns||1);applyDocumentExtras(data);updateStats();updateOutline();queueAutoSave()}
function restore(){const saved=localStorage.getItem(STORAGE_KEY);if(saved){try{loadDocumentData(JSON.parse(saved))}catch{localStorage.removeItem(STORAGE_KEY)}}if(localStorage.getItem('myword2026-theme')==='dark'){document.body.classList.add('dark');document.querySelector('#themeButton').textContent='☀️'}updateStats();updateOutline()}
restore();
showRibbon('home');
window.addEventListener('pagehide',()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(getDocumentData()));localStorage.setItem('myword2026-emergency-backup',JSON.stringify({...getDocumentData(),savedAt:new Date().toISOString()}))}catch{}});
