const STORE='mypowerpoint2026-project';
const canvas=document.querySelector('#slideCanvas'),titleBox=document.querySelector('#slideTitle'),bodyBox=document.querySelector('#slideBody');
const notesInput=document.querySelector('#notesInput'),slideList=document.querySelector('#slideList'),saveStatus=document.querySelector('#saveStatus');
let slides=[newSlide()],current=0,presentIndex=0,saveTimer,dragIndex=null,presentStarted=0,timerId=null,autoTimer=null,copiedStyle=null,selectedImage=null,selectedSlides=new Set(),rehearsalMode=false,slideShownAt=0;
let history=[],future=[],restoringHistory=false;

function newSlide(){return{title:'Заголовок презентации',body:'Нажмите здесь, чтобы добавить текст',notes:'',section:'',state:'draft',accent:'#f97316',theme:'light',layout:'title-content',transition:'fade',animation:'fade-up',background:'',aspect:'wide',hidden:false,duration:5,rehearsed:0,titleStyle:{},bodyStyle:{}}}
function saveCurrent(){if(!slides[current])return;const s=slides[current];s.title=titleBox.innerHTML;s.body=bodyBox.innerHTML;s.notes=notesInput.value;s.titleStyle=pickStyle(titleBox);s.bodyStyle=pickStyle(bodyBox)}
function pickStyle(el){return{fontFamily:el.style.fontFamily,fontSize:el.style.fontSize,color:el.style.color,textAlign:el.style.textAlign,fontWeight:el.style.fontWeight,fontStyle:el.style.fontStyle,textDecoration:el.style.textDecoration}}
function loadSlide(index){if(index<0||index>=slides.length)return;saveCurrent();current=index;const s=slides[current];s.layout=s.layout||'title-content';s.transition=s.transition||'fade';s.animation=s.animation||'fade-up';s.background=s.background||'';s.aspect=s.aspect||'wide';s.duration=s.duration||5;s.state=s.state||'draft';s.accent=s.accent||'#f97316';titleBox.innerHTML=s.title;bodyBox.innerHTML=s.body;notesInput.value=s.notes||'';resetStyle(titleBox,s.titleStyle);resetStyle(bodyBox,s.bodyStyle);canvas.className=`slide-canvas theme-${s.theme} layout-${s.layout} aspect-${s.aspect}`;canvas.style.background=s.background||'';canvas.style.setProperty('--slide-accent',s.accent);document.querySelector('#backgroundColor').value=s.background||'#ffffff';document.querySelector('#accentColor').value=s.accent;document.querySelector('#slideState').value=s.state;document.querySelector('#aspectSelect').value=s.aspect;document.querySelector('#slideDuration').value=s.duration;document.querySelector('#sectionName').value=s.section||'';document.querySelector('#hideSlideBtn').textContent=s.hidden?'🚫 Показать':'👁 Скрыть';document.querySelector('#layoutSelect').value=s.layout;document.querySelector('#transitionSelect').value=s.transition;document.querySelector('#animationSelect').value=s.animation;document.querySelector('#slideNumber').textContent=current+1;document.querySelector('#slideStatus').textContent=`Слайд ${current+1} из ${slides.length} · ${s.state==='ready'?'Готово':'Черновик'}`;document.querySelectorAll('.theme-dot').forEach(b=>b.classList.toggle('active',b.dataset.theme===s.theme));renderThumbnails()}
function resetStyle(el,style){el.removeAttribute('style');Object.assign(el.style,style||{})}
function renderThumbnails(){slideList.innerHTML='';let lastSection=null;slides.forEach((s,i)=>{if(s.section&&s.section!==lastSection){const label=document.createElement('div');label.className='section-label';label.textContent=s.section;slideList.append(label);lastSection=s.section}const item=document.createElement('div');item.className='thumbnail-item'+(i===current?' active':'')+(s.hidden?' is-hidden':'')+(selectedSlides.has(i)?' selected':'');item.draggable=true;item.dataset.index=i;item.innerHTML=`<input class="slide-check" type="checkbox" ${selectedSlides.has(i)?'checked':''} aria-label="Выбрать слайд ${i+1}"><span class="drag-handle">⋮⋮</span><span class="thumb-number">${i+1}</span><div class="thumbnail theme-${s.theme} layout-${s.layout||'title-content'}" style="${s.background?`background:${s.background}`:''}"><strong>${plain(s.title)||'Без заголовка'}</strong><p>${plain(s.body)}</p></div>`;item.querySelector('.slide-check').onclick=e=>{e.stopPropagation();e.target.checked?selectedSlides.add(i):selectedSlides.delete(i);renderThumbnails()};item.onclick=()=>loadSlide(i);item.ondragstart=()=>{saveCurrent();dragIndex=i;item.classList.add('dragging')};item.ondragend=()=>{dragIndex=null;item.classList.remove('dragging')};item.ondragover=e=>e.preventDefault();item.ondrop=e=>{e.preventDefault();if(dragIndex===null||dragIndex===i)return;rememberProject();const moved=slides.splice(dragIndex,1)[0];slides.splice(i,0,moved);selectedSlides.clear();current=i;loadSlide(i);queueSave()};slideList.append(item)});document.querySelector('#selectedCount').textContent=selectedSlides.size}
document.querySelector('#slideSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.thumbnail-item').forEach((item,i)=>item.hidden=q&&!`${plain(slides[i].title)} ${plain(slides[i].body)} ${slides[i].notes||''}`.toLowerCase().includes(q))};
function plain(html){const div=document.createElement('div');div.innerHTML=html;return div.textContent.slice(0,100)}
function changed(){saveCurrent();renderThumbnails();queueSave()}
titleBox.addEventListener('input',changed);bodyBox.addEventListener('input',changed);notesInput.addEventListener('input',changed);document.querySelector('#projectTitle').addEventListener('input',queueSave);
function queueSave(){saveStatus.textContent='Сохранение…';const projectName=document.querySelector('#projectTitle').value||'Презентация 1',titleLabel=document.querySelector('.document-name strong');if(titleLabel)titleLabel.textContent=projectName;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{saveCurrent();localStorage.setItem(STORE,JSON.stringify({title:document.querySelector('#projectTitle').value,slides}));saveStatus.textContent='Презентация сохранена'},450)}
function snapshot(){saveCurrent();return JSON.stringify({slides,current,title:document.querySelector('#projectTitle').value})}
function rememberProject(){if(restoringHistory)return;history.push(snapshot());if(history.length>40)history.shift();future=[];updateHistoryButtons()}
function restoreSnapshot(data){restoringHistory=true;const state=JSON.parse(data);slides=state.slides;current=Math.min(state.current,slides.length-1);document.querySelector('#projectTitle').value=state.title;loadSlide(current);queueSave();restoringHistory=false;updateHistoryButtons()}
function undoProject(){if(!history.length)return;future.push(snapshot());restoreSnapshot(history.pop())}
function redoProject(){if(!future.length)return;history.push(snapshot());restoreSnapshot(future.pop())}
function updateHistoryButtons(){document.querySelector('#undoBtn').disabled=!history.length;document.querySelector('#redoBtn').disabled=!future.length}
document.querySelector('#undoBtn').onclick=undoProject;document.querySelector('#redoBtn').onclick=redoProject;

document.querySelector('#addSlideBtn').onclick=()=>{rememberProject();slides.splice(current+1,0,newSlide());loadSlide(current+1);queueSave()};
document.querySelector('#duplicateBtn').onclick=()=>{rememberProject();slides.splice(current+1,0,structuredClone(slides[current]));loadSlide(current+1);queueSave()};
function moveSlide(step){const next=current+step;if(next<0||next>=slides.length)return;rememberProject();[slides[current],slides[next]]=[slides[next],slides[current]];current=next;loadSlide(current);queueSave()}
document.querySelector('#moveUpBtn').onclick=()=>moveSlide(-1);document.querySelector('#moveDownBtn').onclick=()=>moveSlide(1);
document.querySelector('#deleteBtn').onclick=()=>{if(slides.length===1){showToast('В презентации должен остаться хотя бы один слайд');return}if(!confirm('Удалить выбранный слайд?'))return;rememberProject();slides.splice(current,1);loadSlide(Math.min(current,slides.length-1));queueSave()};
document.querySelector('#hideSlideBtn').onclick=()=>{rememberProject();slides[current].hidden=!slides[current].hidden;loadSlide(current);changed()};document.querySelector('#slideDuration').onchange=e=>{slides[current].duration=Math.max(1,Math.min(120,Number(e.target.value)||5));changed()};
document.querySelector('#sectionName').onchange=e=>{rememberProject();slides[current].section=e.target.value.trim();changed()};document.querySelector('#selectAllBtn').onclick=()=>{selectedSlides=selectedSlides.size===slides.length?new Set():new Set(slides.map((_,i)=>i));renderThumbnails()};document.querySelector('#bulkHideBtn').onclick=()=>{if(!selectedSlides.size)return showToast('Выберите слайды');rememberProject();selectedSlides.forEach(i=>slides[i].hidden=true);selectedSlides.clear();loadSlide(current);changed();showToast('Выбранные слайды скрыты')};document.querySelector('#bulkDeleteBtn').onclick=()=>{if(!selectedSlides.size)return showToast('Выберите слайды');if(slides.length-selectedSlides.size<1)return showToast('Должен остаться хотя бы один слайд');if(!confirm(`Удалить выбранные слайды: ${selectedSlides.size}?`))return;rememberProject();slides=slides.filter((_,i)=>!selectedSlides.has(i));selectedSlides.clear();current=Math.min(current,slides.length-1);loadSlide(current);queueSave()};
document.querySelector('#slideState').onchange=e=>{slides[current].state=e.target.value;changed();loadSlide(current)};document.querySelector('#accentColor').oninput=e=>{slides[current].accent=e.target.value;canvas.style.setProperty('--slide-accent',e.target.value);changed()};document.querySelector('#blockSelect').onchange=e=>{const type=e.target.value;if(!type)return;rememberProject();const blocks={kpi:'<div class="kpi-grid"><div><b>+24%</b><span>Рост</span></div><div><b>1 250</b><span>Клиенты</span></div><div><b>98%</b><span>Качество</span></div></div>',quote:'<blockquote class="modern-quote">«Главная цитата вашей презентации»<cite>— Автор</cite></blockquote>',steps:'<div class="steps-grid"><div><b>1</b><span>Первый шаг</span></div><div><b>2</b><span>Второй шаг</span></div><div><b>3</b><span>Результат</span></div></div>'};bodyBox.innerHTML+=blocks[type];e.target.value='';changed();showToast('Готовый блок добавлен')};
document.querySelectorAll('.theme-dot').forEach(b=>b.onclick=()=>{slides[current].theme=b.dataset.theme;canvas.className=`slide-canvas theme-${b.dataset.theme} layout-${slides[current].layout||'title-content'}`;document.querySelectorAll('.theme-dot').forEach(x=>x.classList.toggle('active',x===b));changed()});
document.querySelector('#layoutSelect').onchange=e=>{slides[current].layout=e.target.value;canvas.className=`slide-canvas theme-${slides[current].theme} layout-${e.target.value}`;changed()};
document.querySelector('#transitionSelect').onchange=e=>{slides[current].transition=e.target.value;changed()};
document.querySelector('#animationSelect').onchange=e=>{slides[current].animation=e.target.value;changed()};
['layoutSelect','transitionSelect','animationSelect','backgroundColor'].forEach(id=>document.querySelector('#'+id).addEventListener('pointerdown',rememberProject));
document.querySelectorAll('.theme-dot').forEach(button=>button.addEventListener('pointerdown',rememberProject));
document.querySelector('#previewEffectBtn').onclick=()=>previewEffects(canvas,slides[current]);
function previewEffects(area,slide){area.classList.remove('effect-preview',`transition-${slide.transition||'fade'}`,`animation-${slide.animation||'fade-up'}`);void area.offsetWidth;area.classList.add('effect-preview',`transition-${slide.transition||'fade'}`,`animation-${slide.animation||'fade-up'}`);setTimeout(()=>area.classList.remove('effect-preview'),850)}
document.querySelector('#imageBtn').onclick=()=>{bodyBox.focus();document.querySelector('#imageInput').click()};
document.querySelector('#imageInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>4*1024*1024){showToast('Изображение должно быть меньше 4 МБ');return}const reader=new FileReader();reader.onload=()=>{bodyBox.focus();document.execCommand('insertImage',false,reader.result);changed();showToast('Изображение добавлено')};reader.readAsDataURL(file);e.target.value=''};
bodyBox.addEventListener('click',e=>{bodyBox.querySelectorAll('img.selected-image').forEach(img=>img.classList.remove('selected-image'));selectedImage=e.target.closest('img');if(selectedImage)selectedImage.classList.add('selected-image')});
document.querySelector('#imageSizeSelect').onchange=e=>{if(!selectedImage)return showToast('Сначала выберите изображение');selectedImage.style.width=e.target.value+'%';selectedImage.style.height='auto';changed()};
function alignImage(value){if(!selectedImage)return showToast('Сначала выберите изображение');selectedImage.style.display='block';selectedImage.style.marginLeft=value==='left'?'0':value==='center'?'auto':'auto';selectedImage.style.marginRight=value==='right'?'0':value==='center'?'auto':'auto';if(value==='left')selectedImage.style.marginRight='auto';changed()}
document.querySelector('#imageLeftBtn').onclick=()=>alignImage('left');document.querySelector('#imageCenterBtn').onclick=()=>alignImage('center');document.querySelector('#imageRightBtn').onclick=()=>alignImage('right');document.querySelector('#imageDeleteBtn').onclick=()=>{if(!selectedImage)return showToast('Сначала выберите изображение');selectedImage.remove();selectedImage=null;changed()};
document.querySelector('#shapeSelect').onchange=e=>{const type=e.target.value;if(!type)return;rememberProject();const shapes={rectangle:'<span class="shape rectangle" contenteditable="false">Текст</span>',circle:'<span class="shape circle" contenteditable="false">Текст</span>',arrow:'<span class="shape arrow" contenteditable="false">➜</span>'};bodyBox.focus();document.execCommand('insertHTML',false,shapes[type]);e.target.value='';changed();showToast('Фигура добавлена')};
document.querySelector('#templateSelect').onchange=e=>{const type=e.target.value;if(!type)return;rememberProject();const templates={title:{title:'Название презентации',body:'Подзаголовок · Автор · Дата'},section:{title:'Новый раздел',body:'Кратко опишите содержание раздела'},comparison:{title:'Сравнение',body:'<div class="comparison"><div><b>Вариант 1</b><br>Преимущества<br>Особенности</div><div><b>Вариант 2</b><br>Преимущества<br>Особенности</div></div>'},thanks:{title:'Спасибо!',body:'Вопросы и контакты'}};Object.assign(slides[current],templates[type]);slides[current].layout='title-content';e.target.value='';loadSlide(current);changed();showToast('Шаблон применён')};
const chartDialog=document.querySelector('#chartDialog');
document.querySelector('#chartBtn').onclick=()=>chartDialog.showModal();
document.querySelector('#chartForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;const labels=document.querySelector('#chartLabels').value.split(',').map(x=>x.trim()).filter(Boolean),values=document.querySelector('#chartValues').value.split(',').map(Number),type=document.querySelector('#chartType').value;if(!labels.length||values.length!==labels.length||values.some(x=>!Number.isFinite(x))){e.preventDefault();showToast('Проверьте подписи и значения');return}rememberProject();bodyBox.innerHTML+=chartMarkup(type,plain(document.querySelector('#chartTitle').value),labels,values);changed();showToast('Диаграмма добавлена')};
function chartMarkup(type,title,labels,values){const max=Math.max(...values,1),colors=['#f97316','#3b82f6','#8b5cf6','#10b981','#ef4444','#eab308'];if(type==='bar'){const bars=values.map((v,i)=>`<div class="chart-column"><span style="height:${Math.max(4,v/max*100)}%"></span><b>${v}</b><small>${labels[i]}</small></div>`).join('');return`<div class="mini-chart"><strong>${title}</strong><div class="chart-bars">${bars}</div></div>`}if(type==='line'){const pts=values.map((v,i)=>`${10+i*(80/Math.max(1,values.length-1))},${90-v/max*72}`).join(' '),dots=values.map((v,i)=>`<circle cx="${10+i*(80/Math.max(1,values.length-1))}" cy="${90-v/max*72}" r="2.3"/><text x="${10+i*(80/Math.max(1,values.length-1))}" y="98">${labels[i]}</text>`).join('');return`<div class="mini-chart"><strong>${title}</strong><svg class="line-chart" viewBox="0 0 100 104"><polyline points="${pts}"/>${dots}</svg></div>`}const total=values.reduce((a,b)=>a+Math.max(0,b),0)||1;let pos=0;const stops=values.map((v,i)=>{const start=pos;pos+=Math.max(0,v)/total*100;return`${colors[i%colors.length]} ${start}% ${pos}%`}).join(','),legend=labels.map((l,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${l}: ${values[i]}</span>`).join('');return`<div class="mini-chart"><strong>${title}</strong><div class="donut-wrap"><div class="donut-chart" style="background:conic-gradient(${stops})"></div><div class="chart-legend">${legend}</div></div></div>`}
document.querySelector('#aspectSelect').onchange=e=>{rememberProject();slides[current].aspect=e.target.value;loadSlide(current);changed()};
document.querySelector('#copyStyleBtn').onclick=()=>{saveCurrent();const s=slides[current];copiedStyle={theme:s.theme,layout:s.layout,transition:s.transition,animation:s.animation,background:s.background,aspect:s.aspect,accent:s.accent,titleStyle:structuredClone(s.titleStyle),bodyStyle:structuredClone(s.bodyStyle)};showToast('Стиль слайда скопирован')};
document.querySelector('#pasteStyleBtn').onclick=()=>{if(!copiedStyle){showToast('Сначала скопируйте стиль');return}rememberProject();Object.assign(slides[current],structuredClone(copiedStyle));loadSlide(current);changed();showToast('Стиль применён')};
document.querySelector('#applyAllBtn').onclick=()=>{saveCurrent();if(!confirm('Применить тему, фон, акцент, шрифты, формат экрана и эффекты текущего слайда ко всем слайдам?'))return;rememberProject();const s=slides[current],style={theme:s.theme,transition:s.transition,animation:s.animation,background:s.background,accent:s.accent,aspect:s.aspect,titleStyle:structuredClone(s.titleStyle),bodyStyle:structuredClone(s.bodyStyle)};slides.forEach(slide=>Object.assign(slide,structuredClone(style)));loadSlide(current);changed();showToast('Оформление применено ко всем слайдам')};
document.querySelector('#backgroundColor').oninput=e=>{slides[current].background=e.target.value;canvas.style.background=e.target.value;changed()};
document.querySelector('#resetBackgroundBtn').onclick=()=>{rememberProject();slides[current].background='';canvas.style.background='';document.querySelector('#backgroundColor').value='#ffffff';changed()};
document.querySelector('#gridBtn').onclick=e=>{canvas.classList.toggle('show-grid');e.currentTarget.classList.toggle('active',canvas.classList.contains('show-grid'))};

function activeEditor(){return document.activeElement===titleBox?titleBox:document.activeElement===bodyBox?bodyBox:bodyBox}
document.querySelectorAll('[data-command]').forEach(btn=>btn.onclick=()=>{activeEditor().focus();document.execCommand(btn.dataset.command);changed()});
document.querySelector('#linkBtn').onclick=()=>{const url=prompt('Введите адрес ссылки, например https://example.com');if(!url)return;activeEditor().focus();document.execCommand('createLink',false,url);changed()};
document.querySelector('#fontName').onchange=e=>format('fontFamily',e.target.value);document.querySelector('#fontSize').onchange=e=>format('fontSize',e.target.value+'px');document.querySelector('#textColor').oninput=e=>format('color',e.target.value);
function format(prop,value){const el=activeEditor();el.focus();if(window.getSelection().toString()&&['fontFamily','fontSize','color'].includes(prop)){const command=prop==='color'?'foreColor':prop==='fontFamily'?'fontName':'fontSize';document.execCommand(command,false,prop==='fontSize'?'6':value)}else el.style[prop]=value;changed()}

function projectData(){saveCurrent();return{app:'MyPowerPoint 2026',version:12,title:document.querySelector('#projectTitle').value,slides}}
function download(content,name){const blob=new Blob([content],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
document.querySelector('#saveBtn').onclick=()=>download(JSON.stringify(projectData(),null,2),safeName(document.querySelector('#projectTitle').value)+'.json');
async function exportPptx(){if(!window.PptxGenJS)return showToast('Модуль PowerPoint ещё загружается — повторите через несколько секунд');saveCurrent();const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='Kazhi Office 2026';pptx.subject='Презентация';pptx.title=document.querySelector('#projectTitle').value;slides.forEach((item,index)=>{const slide=pptx.addSlide();const backgrounds={light:'F8FAFC',ocean:'075985',sunset:'7C2D5E',night:'17142F'},dark=item.theme!=='light';slide.background={color:(item.background||backgrounds[item.theme]||'F8FAFC').replace('#','')};slide.addText(plain(item.title)||`Слайд ${index+1}`,{x:.7,y:.55,w:11.9,h:.8,fontFace:'Aptos Display',fontSize:28,bold:true,color:dark?'FFFFFF':'182033',margin:0});slide.addText(plain(item.body)||'',{x:.75,y:1.65,w:11.7,h:4.7,fontFace:'Aptos',fontSize:18,color:dark?'F8FAFC':'263449',breakLine:false,margin:.08,valign:'top'});slide.addText(String(index+1),{x:12.1,y:7,w:.5,h:.25,fontSize:9,color:dark?'CBD5E1':'64748B',align:'right',margin:0});if(item.notes)pptx.defineNotesMaster&&slide.addNotes?.(item.notes)});await pptx.writeFile({fileName:safeName(document.querySelector('#projectTitle').value)+'.pptx'});showToast('Презентация PPTX сохранена')}
document.querySelector('#notesExportBtn').onclick=()=>{saveCurrent();const text=slides.map((s,i)=>`СЛАЙД ${i+1}: ${plain(s.title)}\n${s.notes||'Заметок нет'}`).join('\n\n');const blob=new Blob([text],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safeName(document.querySelector('#projectTitle').value)+'-заметки.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
document.querySelector('#outlineBtn').onclick=()=>{saveCurrent();const text=`${document.querySelector('#projectTitle').value}\n${'='.repeat(40)}\n\n`+slides.map((s,i)=>`${s.section?`[${s.section}]\n`:''}${i+1}. ${plain(s.title)}\n   ${plain(s.body)}`).join('\n\n');const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safeName(document.querySelector('#projectTitle').value)+'-структура.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);showToast('Структура презентации сохранена')};
document.querySelector('#htmlBtn').onclick=()=>{const data=JSON.stringify(projectData()).replace(/</g,'\\u003c'),html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${safeName(document.querySelector('#projectTitle').value)}</title><style>html,body{margin:0;height:100%;background:#050505;font-family:Arial;color:white;overflow:hidden}.s{position:relative;width:min(100vw,177.78vh);height:min(100vh,56.25vw);margin:auto;padding:8%;box-sizing:border-box;overflow:hidden}.t{font-size:5vw;font-weight:700}.b{font-size:2.6vw;margin-top:4%}.b img{max-width:100%;max-height:42vh}.n{position:absolute;right:2%;bottom:2%;opacity:.6}.c{position:fixed;bottom:12px;left:50%;transform:translateX(-50%);background:#0009;padding:8px;border-radius:8px}button{font-size:22px;background:#fff2;color:#fff;border:0;padding:8px 16px}</style><body><div id="a"></div><div class="c"><button onclick="go(-1)">‹</button><span id="x"></span><button onclick="go(1)">›</button></div><script>const d=${data};let i=0;function go(v){i=Math.max(0,Math.min(d.slides.length-1,i+v));let s=d.slides[i],a=document.getElementById('a');a.className='s';a.style.background=s.background||({light:'#fff',ocean:'#075985',sunset:'#7c2d5e',night:'#17142f'}[s.theme]||'#fff');a.style.color=s.theme==='light'?'#182033':'#fff';a.innerHTML='<div class="t">'+s.title+'</div><div class="b">'+s.body+'</div><div class="n">'+(i+1)+'</div>';x.textContent=(i+1)+' / '+d.slides.length}document.onkeydown=e=>{if(e.key==='ArrowRight'||e.key===' ')go(1);if(e.key==='ArrowLeft')go(-1)};go(0);<\/script>`;const blob=new Blob([html],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safeName(document.querySelector('#projectTitle').value)+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);showToast('Автономная презентация HTML сохранена')};
document.querySelector('#openBtn').onclick=()=>document.querySelector('#fileInput').click();document.querySelector('#fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.slides)||!d.slides.length)throw Error();slides=d.slides;document.querySelector('#projectTitle').value=d.title||'Презентация';current=0;loadSlide(0);queueSave();showToast('Презентация открыта')}catch{showToast('Не удалось открыть файл')}};r.readAsText(file);e.target.value=''};
document.querySelector('#newProjectBtn').onclick=()=>{if(!confirm('Создать новую презентацию?'))return;slides=[newSlide()];current=0;document.querySelector('#projectTitle').value='Новая презентация';loadSlide(0);queueSave()};
const safeName=n=>(n.trim()||'Презентация').replace(/[\\/:*?"<>|]/g,'-');

document.querySelector('#presentBtn').onclick=()=>startPresentation(current,false);document.querySelector('#rehearseBtn').onclick=()=>startPresentation(current,true);document.querySelector('#exitBtn').onclick=exitPresentation;document.querySelector('#nextBtn').onclick=()=>showPresent(nextVisible(presentIndex,1));document.querySelector('#prevBtn').onclick=()=>showPresent(nextVisible(presentIndex,-1));
function nextVisible(from,step){let i=from+step;while(i>=0&&i<slides.length&&slides[i].hidden)i+=step;return i}
function startPresentation(index,rehearse=false){saveCurrent();rehearsalMode=rehearse;slideShownAt=0;presentIndex=slides[index]?.hidden?nextVisible(index-1,1):index;presentStarted=Date.now();clearInterval(timerId);clearTimeout(autoTimer);updatePresentTimer();timerId=setInterval(updatePresentTimer,1000);document.querySelector('#rehearsalBadge').classList.toggle('hidden',!rehearsalMode);document.querySelector('#presenter').classList.remove('hidden');showPresent(presentIndex);document.querySelector('#presenter').focus();document.querySelector('#presenter').requestFullscreen?.().catch(()=>{})}
function recordRehearsal(){if(rehearsalMode&&slideShownAt&&slides[presentIndex])slides[presentIndex].rehearsed=Math.max(1,Math.round((Date.now()-slideShownAt)/1000));slideShownAt=0}function showPresent(index){recordRehearsal();if(index<0){return}if(index>=slides.length){exitPresentation();return}presentIndex=index;slideShownAt=Date.now();const s=slides[index],area=document.querySelector('#presentSlide');area.className=`present-slide theme-${s.theme} layout-${s.layout||'title-content'} aspect-${s.aspect||'wide'} transition-${s.transition||'fade'} animation-${s.animation||'fade-up'}`;area.style.background=s.background||'';area.style.setProperty('--slide-accent',s.accent||'#f97316');area.innerHTML=`<div class="slide-title" style="${styleText(s.titleStyle)}">${s.title}</div><div class="slide-body" style="${styleText(s.bodyStyle)}">${s.body}</div><div class="slide-number">${index+1}</div>`;document.querySelector('#presentNotes').textContent=s.notes||'Для этого слайда заметок нет';document.querySelector('#presentProgress').style.width=((index+1)/slides.length*100)+'%';void area.offsetWidth;area.classList.add('effect-preview');document.querySelector('#presentCounter').textContent=`${index+1} / ${slides.length}`;clearTimeout(autoTimer);const globalDelay=Number(document.querySelector('#autoPlaySelect').value);if(globalDelay)autoTimer=setTimeout(()=>showPresent(nextVisible(presentIndex,1)),(s.duration||globalDelay)*1000)}
document.querySelector('#notesBtn').onclick=()=>document.querySelector('#presentNotes').classList.toggle('hidden');
let laserOn=false;const presenter=document.querySelector('#presenter'),laserDot=document.querySelector('#laserDot');function toggleLaser(){laserOn=!laserOn;laserDot.classList.toggle('hidden',!laserOn);presenter.classList.toggle('laser-mode',laserOn);document.querySelector('#laserBtn').classList.toggle('active',laserOn)}document.querySelector('#laserBtn').onclick=toggleLaser;presenter.addEventListener('pointermove',e=>{if(!laserOn)return;laserDot.style.left=e.clientX+'px';laserDot.style.top=e.clientY+'px'});presenter.addEventListener('pointerleave',()=>laserDot.classList.add('hidden'));presenter.addEventListener('pointerenter',()=>laserDot.classList.toggle('hidden',!laserOn));
let penOn=false,drawing=false,lastPoint=null;const drawCanvas=document.querySelector('#drawCanvas'),drawCtx=drawCanvas.getContext('2d');function sizeDrawCanvas(){drawCanvas.width=innerWidth;drawCanvas.height=innerHeight;drawCtx.lineWidth=5;drawCtx.lineCap='round';drawCtx.strokeStyle='#ff2d2d'}function togglePen(){penOn=!penOn;if(penOn&&laserOn)toggleLaser();drawCanvas.classList.toggle('active',penOn);document.querySelector('#penBtn').classList.toggle('active',penOn)}document.querySelector('#penBtn').onclick=togglePen;document.querySelector('#clearDrawBtn').onclick=()=>drawCtx.clearRect(0,0,drawCanvas.width,drawCanvas.height);drawCanvas.onpointerdown=e=>{if(!penOn)return;drawing=true;lastPoint=[e.clientX,e.clientY];drawCanvas.setPointerCapture(e.pointerId)};drawCanvas.onpointermove=e=>{if(!drawing)return;drawCtx.beginPath();drawCtx.moveTo(...lastPoint);drawCtx.lineTo(e.clientX,e.clientY);drawCtx.stroke();lastPoint=[e.clientX,e.clientY]};drawCanvas.onpointerup=()=>drawing=false;window.addEventListener('resize',sizeDrawCanvas);sizeDrawCanvas();
function updatePresentTimer(){const sec=Math.floor((Date.now()-presentStarted)/1000),min=Math.floor(sec/60);document.querySelector('#presentTimer').textContent=`${String(min).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function styleText(style={}){return Object.entries(style).filter(([,v])=>v).map(([k,v])=>`${k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}:${String(v).replace(/[;{}]/g,'')}`).join(';')}
function exitPresentation(){recordRehearsal();if(rehearsalMode){queueSave();showToast('Время репетиции сохранено')}rehearsalMode=false;slideShownAt=0;clearInterval(timerId);clearInterval(autoTimer);laserOn=false;penOn=false;laserDot.classList.add('hidden');presenter.classList.remove('laser-mode');drawCanvas.classList.remove('active');drawCtx.clearRect(0,0,drawCanvas.width,drawCanvas.height);document.querySelector('#presenter').classList.add('hidden');if(document.fullscreenElement)document.exitFullscreen?.()}
document.addEventListener('keydown',e=>{if(document.querySelector('#presenter').classList.contains('hidden'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();showPresent(nextVisible(presentIndex,1))}if(['ArrowLeft','PageUp'].includes(e.key))showPresent(nextVisible(presentIndex,-1));if(e.key.toLowerCase()==='l')toggleLaser();if(e.key==='Escape')exitPresentation()});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.querySelector('#presenter').classList.add('hidden')});
document.querySelector('#pdfBtn').onclick=()=>{saveCurrent();let deck=document.querySelector('#printDeck');if(!deck){deck=document.createElement('section');deck.id='printDeck';deck.className='print-deck';document.body.append(deck)}deck.innerHTML=slides.map((s,i)=>`<article class="print-page theme-${s.theme} layout-${s.layout||'title-content'}" style="${s.background?`background:${s.background}`:''}"><div class="slide-title" style="${styleText(s.titleStyle)}">${s.title}</div><div class="slide-body" style="${styleText(s.bodyStyle)}">${s.body}</div><div class="slide-number">${i+1}</div></article>`).join('');window.print()};

document.querySelector('#darkBtn').onclick=e=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');e.currentTarget.textContent=dark?'☀️':'🌙';localStorage.setItem('mypowerpoint-dark',dark?'1':'0')};
document.querySelector('#focusBtn').onclick=()=>{document.body.classList.toggle('focus-mode');document.querySelector('#focusBtn').classList.toggle('active',document.body.classList.contains('focus-mode'));showToast(document.body.classList.contains('focus-mode')?'Режим фокуса включён':'Режим фокуса выключен')};
document.querySelector('#shortcutsBtn').onclick=()=>document.querySelector('#shortcutsDialog').showModal();
const overviewDialog=document.querySelector('#overviewDialog');document.querySelector('#overviewBtn').onclick=()=>{saveCurrent();document.querySelector('#overviewGrid').innerHTML=slides.map((s,i)=>`<button type="button" data-slide="${i}" class="overview-card theme-${s.theme}${s.hidden?' is-hidden':''}"><span>${i+1}</span><strong>${plain(s.title)||'Без заголовка'}</strong><small>${s.section||'Без раздела'}</small></button>`).join('');overviewDialog.showModal()};document.querySelector('#overviewGrid').onclick=e=>{const card=e.target.closest('[data-slide]');if(!card)return;overviewDialog.close();loadSlide(Number(card.dataset.slide))};
const replaceDialog=document.querySelector('#replaceDialog');function replaceTextNodes(html,find,replacement,caseSensitive){const box=document.createElement('div');box.innerHTML=html;const flags=caseSensitive?'g':'gi',pattern=new RegExp(find.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),flags);let count=0;const walker=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const next=node.nodeValue.replace(pattern,()=>{count++;return replacement});node.nodeValue=next});return{html:box.innerHTML,count}}
document.querySelector('#replaceForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;const find=document.querySelector('#findText').value,replacement=document.querySelector('#replaceText').value,caseSensitive=document.querySelector('#caseSensitive').checked;if(!find){e.preventDefault();return}rememberProject();saveCurrent();let total=0;slides.forEach(s=>{let r=replaceTextNodes(s.title,find,replacement,caseSensitive);s.title=r.html;total+=r.count;r=replaceTextNodes(s.body,find,replacement,caseSensitive);s.body=r.html;total+=r.count;s.notes=(s.notes||'').replace(new RegExp(find.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),caseSensitive?'g':'gi'),()=>{total++;return replacement})});loadSlide(current);queueSave();showToast(total?`Заменено: ${total}`:'Совпадений не найдено')};
document.querySelector('#checkBtn').onclick=()=>{saveCurrent();const issues=[];slides.forEach((s,i)=>{if(!plain(s.title).trim())issues.push(`Слайд ${i+1}: нет заголовка`);const box=document.createElement('div');box.innerHTML=s.body;box.querySelectorAll('img').forEach(img=>{if(!img.alt)issues.push(`Слайд ${i+1}: у изображения нет описания`)});if(plain(s.body).length>450)issues.push(`Слайд ${i+1}: слишком много текста`);if(s.hidden)issues.push(`Слайд ${i+1}: слайд скрыт`)});document.querySelector('#checkResults').innerHTML=issues.length?issues.map(x=>`<div class="check-issue">⚠️ ${x}</div>`).join(''):'<div class="check-ok">✓ Ошибок не найдено</div>';document.querySelector('#checkDialog').showModal()};
const commandDialog=document.querySelector('#commandDialog'),commandSearch=document.querySelector('#commandSearch'),commandList=document.querySelector('#commandList');const commands=[['Новый слайд',()=>document.querySelector('#addSlideBtn').click()],['Копировать слайд',()=>document.querySelector('#duplicateBtn').click()],['Показ презентации',()=>document.querySelector('#presentBtn').click()],['Обзор слайдов',()=>document.querySelector('#overviewBtn').click()],['Найти и заменить',()=>replaceDialog.showModal()],['Проверить доступность',()=>document.querySelector('#checkBtn').click()],['Экспорт структуры',()=>document.querySelector('#outlineBtn').click()],['Режим фокуса',()=>document.querySelector('#focusBtn').click()],['Тёмная тема',()=>document.querySelector('#darkBtn').click()]];function renderCommands(){const q=commandSearch.value.toLowerCase();commandList.innerHTML=commands.map((c,i)=>({c,i})).filter(x=>x.c[0].toLowerCase().includes(q)).map(x=>`<button type="button" data-command-index="${x.i}">${x.c[0]}<span>↵</span></button>`).join('')||'<p>Команда не найдена</p>'}function openCommands(){commandSearch.value='';renderCommands();commandDialog.showModal();setTimeout(()=>commandSearch.focus(),30)}document.querySelector('#commandBtn').onclick=openCommands;commandSearch.oninput=renderCommands;commandList.onclick=e=>{const b=e.target.closest('[data-command-index]');if(!b)return;commandDialog.close();commands[Number(b.dataset.commandIndex)][1]()};commandSearch.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commandList.querySelector('button')?.click()}};
document.querySelector('#collapseBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('collapsed');document.querySelector('#zoom').oninput=e=>{canvas.style.transform=`scale(${e.target.value/100})`;document.querySelector('#zoomOut').value=e.target.value+'%'};
document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>showToast(b.dataset.info));function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2100)}
document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{const el=document.querySelector('#'+b.dataset.focus);el.scrollIntoView({behavior:'smooth',inline:'center'});el.focus()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands();return}if(e.key==='Escape'&&document.body.classList.contains('focus-mode')&&document.querySelector('#presenter').classList.contains('hidden')){document.body.classList.remove('focus-mode');document.querySelector('#focusBtn').classList.remove('active');return}if(e.key==='F5'&&document.querySelector('#presenter').classList.contains('hidden')){e.preventDefault();startPresentation(current);return}if(!e.ctrlKey&&!e.metaKey)return;const key=e.key.toLowerCase();if(key==='s'){e.preventDefault();document.querySelector('#saveBtn').click()}if(key==='d'){e.preventDefault();document.querySelector('#duplicateBtn').click()}if(key==='z'&&!e.shiftKey&&!document.activeElement.isContentEditable){e.preventDefault();undoProject()}if((key==='y'||(key==='z'&&e.shiftKey))&&!document.activeElement.isContentEditable){e.preventDefault();redoProject()}});
document.querySelector('#statsBtn').onclick=()=>{saveCurrent();const words=slides.reduce((n,s)=>n+(plain(s.title)+' '+plain(s.body)).trim().split(/\s+/).filter(Boolean).length,0),images=slides.reduce((n,s)=>{const box=document.createElement('div');box.innerHTML=s.body;return n+box.querySelectorAll('img').length},0),ready=slides.filter(s=>s.state==='ready').length,planned=slides.reduce((n,s)=>n+(Number(s.duration)||5),0),rehearsed=slides.reduce((n,s)=>n+(Number(s.rehearsed)||0),0);document.querySelector('#statsGrid').innerHTML=[[slides.length,'Слайдов'],[words,'Слов'],[images,'Изображений'],[ready,'Готово'],[Math.round(planned/60)+' мин','План'],[rehearsed?Math.round(rehearsed/60)+' мин':'—','Репетиция']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');document.querySelector('#rehearsalList').innerHTML=slides.some(s=>s.rehearsed)?'<h4>Время по слайдам</h4>'+slides.map((s,i)=>`<div><span>${i+1}. ${plain(s.title)}</span><b>${s.rehearsed||0} сек.</b></div>`).join(''):'<p>Запустите «Репетицию», чтобы записать время каждого слайда.</p>';document.querySelector('#statsDialog').showModal()};
function restore(){try{const d=JSON.parse(localStorage.getItem(STORE));if(d?.slides?.length){slides=d.slides;document.querySelector('#projectTitle').value=d.title||'Презентация'}}catch{}document.body.classList.add('dark');document.querySelector('#darkBtn').textContent='☀️';loadSlide(0);updateHistoryButtons()}restore();

const ribbonGroups=[...document.querySelectorAll('.ribbon>.group')];
const ribbonMap={home:[0,1,4,5,10],insert:[2,5,9,10],design:[6,7,8],transitions:[3,10],animations:[3,4],slideshow:[1,10],record:[10],review:[5,10],view:[1,8,10]};
function activateRibbon(name='home'){document.querySelectorAll('[data-ribbon]').forEach(b=>b.classList.toggle('active',b.dataset.ribbon===name));ribbonGroups.forEach((g,i)=>g.classList.toggle('ribbon-hidden',!(ribbonMap[name]||[]).includes(i)));document.querySelector('.ribbon').dataset.active=name}
document.querySelectorAll('[data-ribbon]').forEach(button=>button.onclick=()=>activateRibbon(button.dataset.ribbon));activateRibbon('home');

const appActions={new:()=>document.querySelector('#newProjectBtn').click(),template:()=>{activateRibbon('insert');document.querySelector('#templateSelect').focus()},open:()=>document.querySelector('#openBtn').click(),save:()=>document.querySelector('#saveBtn').click(),pptx:exportPptx,html:()=>document.querySelector('#htmlBtn').click(),outline:()=>document.querySelector('#outlineBtn').click(),print:()=>document.querySelector('#pdfBtn').click(),stats:()=>document.querySelector('#statsBtn').click(),undo:()=>document.querySelector('#undoBtn').click(),redo:()=>document.querySelector('#redoBtn').click(),'copy-slide':()=>document.querySelector('#duplicateBtn').click(),'delete-slide':()=>document.querySelector('#deleteBtn').click(),replace:()=>document.querySelector('#replaceDialog').showModal(),normal:()=>{document.body.classList.remove('focus-mode');activateRibbon('home')},overview:()=>document.querySelector('#overviewBtn').click(),notes:()=>document.querySelector('.notes').scrollIntoView({behavior:'smooth'}),focus:()=>document.querySelector('#focusBtn').click(),'new-slide':()=>document.querySelector('#addSlideBtn').click(),image:()=>document.querySelector('#imageBtn').click(),chart:()=>document.querySelector('#chartBtn').click(),shape:()=>{activateRibbon('insert');document.querySelector('#shapeSelect').focus()},link:()=>document.querySelector('#linkBtn').click(),check:()=>document.querySelector('#checkBtn').click(),shortcuts:()=>document.querySelector('#shortcutsBtn').click(),home:()=>activateRibbon('home')};
document.addEventListener('click',e=>{const trigger=e.target.closest('.menu-trigger');if(trigger){const menu=trigger.parentElement;document.querySelectorAll('.mac-menu.open').forEach(x=>{if(x!==menu)x.classList.remove('open')});menu.classList.toggle('open');e.stopPropagation();return}const action=e.target.closest('[data-app-action]');if(action){document.querySelectorAll('.mac-menu.open').forEach(x=>x.classList.remove('open'));appActions[action.dataset.appAction]?.();return}const jump=e.target.closest('[data-tab-jump]');if(jump){activateRibbon(jump.dataset.tabJump);return}if(!e.target.closest('.mac-menu'))document.querySelectorAll('.mac-menu.open').forEach(x=>x.classList.remove('open'))});
document.querySelector('#projectTitle').addEventListener('input',e=>document.querySelector('.document-name strong').textContent=e.target.value||'Презентация 1');document.querySelector('.document-name strong').textContent=document.querySelector('#projectTitle').value||'Презентация 1';
