const sheet=document.querySelector('#sheet'),formulaInput=document.querySelector('#formulaInput'),nameBox=document.querySelector('#nameBox');
const saveStatus=document.querySelector('#saveStatus'),toast=document.querySelector('#toast'),stats=document.querySelector('#selectionStats');
const STORE='myexcel2026-workbook-v2';let rows=30,cols=12,active=null,saveTimer,activeSheet=0,historyReady=false;
const SNAPSHOTS='myexcel2026-snapshots-v1';
let cells={},sheets=[{name:'Лист1',rows,cols,cells}],selectedIds=new Set(['A1']);
let undoStack=[],redoStack=[],copiedStyle=null,namedRanges={};

const colName=n=>{let s='';while(n>=0){s=String.fromCharCode(n%26+65)+s;n=Math.floor(n/26)-1}return s};
const cellId=(r,c)=>colName(c)+(r+1);
function buildSheet(){sheet.innerHTML='';sheet.classList.toggle('freeze-first-row',!!sheets[activeSheet]?.freezeFirstRow);sheet.classList.toggle('freeze-first-col',!!sheets[activeSheet]?.freezeFirstCol);sheet.classList.toggle('protected',!!sheets[activeSheet]?.protected);const protectBtn=document.querySelector('#protectBtn');if(protectBtn)protectBtn.textContent=sheets[activeSheet]?.protected?'🔓 Снять защиту':'🔒 Защита';sheet.style.gridTemplateColumns=`44px repeat(${cols},var(--cell-width,105px))`;sheet.append(make('div','corner',''));
  for(let c=0;c<cols;c++){const head=make('div','column-head',colName(c));head.onclick=()=>selectColumn(c);sheet.append(head)}
  for(let r=0;r<rows;r++){const rowHead=make('div','row-head',r+1);rowHead.onclick=()=>selectRow(r);if(sheets[activeSheet]?.freezeRow===r)rowHead.classList.add('frozen-row-head');sheet.append(rowHead);for(let c=0;c<cols;c++){const id=cellId(r,c),el=make('div','cell','');if(r===0)el.classList.add('first-data-row');if(sheets[activeSheet]?.freezeRow===r)el.classList.add('frozen-data-row');el.contentEditable=sheets[activeSheet]?.protected?'false':'true';el.dataset.id=id;applyCell(el,id);applyMerge(el,id);el.addEventListener('mousedown',e=>{if(e.shiftKey){e.preventDefault();selectRangeTo(id)}});el.addEventListener('click',()=>toggleCheckbox(id));el.addEventListener('dblclick',()=>openCellAction(id));el.addEventListener('focus',()=>selectCell(el));el.addEventListener('beforeinput',e=>{if(sheets[activeSheet]?.protected)return e.preventDefault();if(!el.dataset.historyCaptured){captureHistory();el.dataset.historyCaptured='1'}});el.addEventListener('input',()=>{setCellFromElement(el);queueSave()});el.addEventListener('keydown',handleKeys);el.addEventListener('blur',()=>renderValues());sheet.append(el)}}applyFilter();applySelection()
}
function make(tag,className,text){const el=document.createElement(tag);el.className=className;el.textContent=text;return el}
function getData(id){return cells[id]||(cells[id]={value:'',style:{}})}
function applyCell(el,id){const data=getData(id);el.textContent=data.type==='checkbox'?(data.checked?'☑':'☐'):data.value;el.classList.toggle('checkbox-cell',data.type==='checkbox');el.classList.toggle('has-note',!!data.note);el.classList.toggle('has-validation',!!data.validation?.length);el.classList.toggle('has-link',!!data.link);el.title=[data.note,data.validation?.length?'Список: '+data.validation.join(', '):'',data.link||''].filter(Boolean).join('\n');Object.assign(el.style,data.style||{})}
function openCellAction(id){const data=getData(id);if(data.link){window.open(data.link,'_blank','noopener');return}chooseValidation(id)}
function applyMerge(el,id){const data=getData(id);if(data.mergeParent){el.classList.add('merge-hidden');return}if(data.merge){el.classList.add('merged-cell');el.style.width=`calc(var(--cell-width,105px) * ${data.merge.cols})`;el.style.height=`${30*data.merge.rows}px`}}
function chooseValidation(id){const data=getData(id);if(!data.validation?.length||sheets[activeSheet]?.protected)return;const answer=prompt('Выберите значение:\n'+data.validation.map((v,i)=>`${i+1}. ${v}`).join('\n'),data.value||data.validation[0]);if(answer===null)return;const index=Number(answer)-1,value=data.validation.includes(answer)?answer:data.validation[index];if(value===undefined)return showToast('Выберите пункт из списка');captureHistory();data.value=value;buildSheet();renderValues();queueSave()}
function toggleCheckbox(id){const data=getData(id);if(data.type!=='checkbox'||sheets[activeSheet]?.protected)return;captureHistory();data.checked=!data.checked;data.value=data.checked?'TRUE':'FALSE';buildSheet();renderValues();queueSave()}
function setCellFromElement(el){const data=getData(el.dataset.id);data.value=el.textContent;formulaInput.value=data.value;updateStats()}
function selectCell(el){document.querySelector('.cell.selected')?.classList.remove('selected');active=el;selectedIds=new Set([el.dataset.id]);el.dataset.historyCaptured='';el.classList.add('selected');applySelection();nameBox.textContent=el.dataset.id;formulaInput.value=getData(el.dataset.id).value;updateStats()}
function cellPosition(id){const m=id.match(/([A-Z]+)(\d+)/);return{r:+m[2]-1,c:lettersToNumber(m[1])}}
function selectRangeTo(id){const start=cellPosition(active?.dataset.id||'A1'),end=cellPosition(id);selectedIds=new Set();for(let r=Math.min(start.r,end.r);r<=Math.max(start.r,end.r);r++)for(let c=Math.min(start.c,end.c);c<=Math.max(start.c,end.c);c++)selectedIds.add(cellId(r,c));applySelection();nameBox.textContent=`${active?.dataset.id||'A1'}:${id}`;updateStats()}
function selectRow(r){selectedIds=new Set();for(let c=0;c<cols;c++)selectedIds.add(cellId(r,c));active=document.querySelector(`[data-id="${cellId(r,0)}"]`);applySelection();nameBox.textContent=`Строка ${r+1}`;updateStats()}
function selectColumn(c){selectedIds=new Set();for(let r=0;r<rows;r++)selectedIds.add(cellId(r,c));active=document.querySelector(`[data-id="${cellId(0,c)}"]`);applySelection();nameBox.textContent=`Столбец ${colName(c)}`;updateStats()}
function applySelection(){document.querySelectorAll('.cell').forEach(el=>el.classList.toggle('range-selected',selectedIds.has(el.dataset.id)&&el!==active))}
function handleKeys(e){const arrows={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(e.key==='Enter'){e.preventDefault();move(1,0)}else if(e.key==='Tab'){e.preventDefault();move(0,e.shiftKey?-1:1)}else if(arrows[e.key]){e.preventDefault();move(...arrows[e.key])}}
function move(dr,dc){if(!active)return;const match=active.dataset.id.match(/([A-Z]+)(\d+)/);const c=lettersToNumber(match[1]),r=+match[2]-1;document.querySelector(`[data-id="${cellId(Math.max(0,Math.min(rows-1,r+dr)),Math.max(0,Math.min(cols-1,c+dc)))}"]`)?.focus()}
function lettersToNumber(s){let n=0;for(const ch of s)n=n*26+ch.charCodeAt(0)-64;return n-1}

formulaInput.addEventListener('focus',()=>formulaInput.dataset.historyCaptured='');formulaInput.addEventListener('beforeinput',()=>{if(active&&!formulaInput.dataset.historyCaptured){captureHistory();formulaInput.dataset.historyCaptured='1'}});formulaInput.addEventListener('input',()=>{if(!active)return;getData(active.dataset.id).value=formulaInput.value;active.textContent=formulaInput.value;queueSave()});
formulaInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();renderValues();active?.focus()}});
function valueOf(id,stack=[]){return valueOfAt(activeSheet,id,stack)}
function valueOfAt(sheetIndex,id,stack=[]){const key=`${sheetIndex}:${id}`;if(stack.includes(key))return '#ЦИКЛ!';const raw=(sheets[sheetIndex]?.cells?.[id]?.value||'').trim();if(!raw.startsWith('='))return raw;try{return calculate(raw.slice(1),[...stack,key],sheetIndex)}catch{return '#ОШИБКА!'}}
function calculate(expression,stack,sheetIndex=activeSheet){let exp=expression.toUpperCase();Object.entries(namedRanges).forEach(([name,range])=>{if(range.sheetIndex===sheetIndex)exp=exp.replace(new RegExp(`\\b${name}\\b`,'g'),`${range.start}:${range.end}`)});exp=exp.replace(/(?:'([^']+)'|([А-ЯЁA-Z0-9_]+))!([A-Z]+\d+)/g,(_,quoted,plain,id)=>{const name=quoted||plain,index=sheets.findIndex(s=>s.name.toUpperCase()===name);const v=parseFloat(valueOfAt(index,id,stack));return Number.isFinite(v)?v:0});exp=exp.replace(/(SUM|AVERAGE|MIN|MAX|COUNT|MEDIAN)\(([A-Z]+\d+):([A-Z]+\d+)\)/g,(_,fn,start,end)=>{const v=rangeValues(start,end,stack,sheetIndex);if(fn==='COUNT')return v.length;if(!v.length)return'0';if(fn==='SUM')return v.reduce((a,b)=>a+b,0);if(fn==='AVERAGE')return v.reduce((a,b)=>a+b,0)/v.length;if(fn==='MIN')return Math.min(...v);if(fn==='MAX')return Math.max(...v);const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2});exp=exp.replace(/IF\(([^,;]+)[,;]([^,;]+)[,;]([^\)]+)\)/g,'(($1)?($2):($3))');exp=exp.replace(/[A-Z]+\d+/g,id=>{const val=parseFloat(valueOfAt(sheetIndex,id,stack));return Number.isFinite(val)?val:0});exp=exp.replace(/ABS\(([^()]+)\)/g,'Math.abs($1)').replace(/SQRT\(([^()]+)\)/g,'Math.sqrt($1)').replace(/POWER\(([^,;]+)[,;]([^\)]+)\)/g,'Math.pow($1,$2)').replace(/ROUND\(([^,;]+)[,;](\d+)\)/g,'(Math.round(($1)*10**$2)/10**$2)');if(!/^[\d+\-*/().,<>=!?:\sA-Za-z]+$/.test(exp)||/[^Mathabspowqrtund\d+\-*/().,<>=!?:\s]/i.test(exp.replace(/Math\.(abs|sqrt|pow|round)/g,'')))throw Error();exp=exp.replace(/([^<>!=])=([^=])/g,'$1==$2');return Function(`"use strict";return (${exp})`)()}
function rangeValues(start,end,stack,sheetIndex=activeSheet){const a=start.match(/([A-Z]+)(\d+)/),b=end.match(/([A-Z]+)(\d+)/);const out=[];for(let r=+a[2]-1;r<=+b[2]-1;r++)for(let c=lettersToNumber(a[1]);c<=lettersToNumber(b[1]);c++){const n=parseFloat(valueOfAt(sheetIndex,cellId(r,c),stack));if(Number.isFinite(n))out.push(n)}return out}
function renderValues(){document.querySelectorAll('.cell').forEach(el=>{if(el===active&&document.activeElement===el)return;const data=getData(el.dataset.id);if(data.type==='checkbox'){el.textContent=data.checked?'☑':'☐';el.classList.remove('formula-error');return}let value=valueOf(el.dataset.id);el.classList.toggle('formula-error',String(value).startsWith('#'));if(data.style?.format==='currency'&&value!==''&&!isNaN(value))value=Number(value).toLocaleString('ru-RU')+' ₸';if(data.style?.format==='percent'&&value!==''&&!isNaN(value))value=Number(value).toLocaleString('ru-RU')+'%';if(data.style?.format==='number'&&value!==''&&!isNaN(value))value=Number(value).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2});if(data.style?.format==='date'&&/^\d{4}-\d{2}-\d{2}$/.test(value)){const [y,m,d]=value.split('-');value=`${d}.${m}.${y}`}el.textContent=value})}
function format(prop,value){if(!active)return;captureHistory();selectedIds.forEach(id=>getData(id).style[prop]=value);document.querySelectorAll('.cell').forEach(el=>{if(selectedIds.has(el.dataset.id))el.style[prop]=value});queueSave()}
document.querySelectorAll('[data-format]').forEach(btn=>btn.onclick=()=>{const p=btn.dataset.format==='bold'?'fontWeight':btn.dataset.format==='italic'?'fontStyle':'textDecoration';const v=p==='fontWeight'?(active?.style[p]==='bold'?'normal':'bold'):p==='fontStyle'?(active?.style[p]==='italic'?'normal':'italic'):(active?.style[p]==='underline'?'none':'underline');format(p,v)});
document.querySelectorAll('[data-align]').forEach(btn=>btn.onclick=()=>format('textAlign',btn.dataset.align));
document.querySelector('#fontName').onchange=e=>format('fontFamily',e.target.value);document.querySelector('#fontSize').onchange=e=>format('fontSize',e.target.value+'px');document.querySelector('#textColor').oninput=e=>format('color',e.target.value);document.querySelector('#fillColor').oninput=e=>format('backgroundColor',e.target.value);
document.querySelector('#currencyBtn').onclick=()=>setNumberFormat('currency');document.querySelector('#percentBtn').onclick=()=>setNumberFormat('percent');document.querySelector('#numberBtn').onclick=()=>setNumberFormat('number');document.querySelector('#dateBtn').onclick=()=>setNumberFormat('date');document.querySelector('#borderBtn').onclick=()=>{if(!active)return;captureHistory();const on=getData([...selectedIds][0]).style.border==='1px solid #667085';selectedIds.forEach(id=>getData(id).style.border=on?'':'1px solid #667085');buildSheet();renderValues();queueSave()};
function setNumberFormat(type){if(!active)return;captureHistory();selectedIds.forEach(id=>getData(id).style.format=type);renderValues();queueSave()}
function quickFormula(fn){if(!selectedIds.size)return showToast('Выделите диапазон');const points=[...selectedIds].map(cellPosition),r1=Math.min(...points.map(p=>p.r)),r2=Math.max(...points.map(p=>p.r)),c1=Math.min(...points.map(p=>p.c)),c2=Math.max(...points.map(p=>p.c)),target=r2>r1?cellId(r2+1,c1):cellId(r1,c2+1);captureHistory();rows=Math.max(rows,r2+2);cols=Math.max(cols,c2+2);getData(target).value=`=${fn}(${cellId(r1,c1)}:${cellId(r2,c2)})`;selectedIds=new Set([target]);buildSheet();renderValues();queueSave();document.querySelector(`[data-id="${target}"]`)?.focus();showToast('Формула добавлена')}
document.querySelector('#quickSumBtn').onclick=()=>quickFormula('SUM');document.querySelector('#quickAvgBtn').onclick=()=>quickFormula('AVERAGE');document.querySelector('#quickMinBtn').onclick=()=>quickFormula('MIN');document.querySelector('#quickMaxBtn').onclick=()=>quickFormula('MAX');
document.querySelector('#namedRangeBtn').onclick=()=>{if(!selectedIds.size)return;const name=(prompt('Название латинскими буквами, например SALES:')||'').trim().toUpperCase();if(!/^[A-Z_][A-Z0-9_]*$/.test(name)||/^[A-Z]+\d+$/.test(name))return name&&showToast('Используйте латинские буквы, цифры и знак _');const points=[...selectedIds].map(cellPosition),start=cellId(Math.min(...points.map(p=>p.r)),Math.min(...points.map(p=>p.c))),end=cellId(Math.max(...points.map(p=>p.r)),Math.max(...points.map(p=>p.c)));captureHistory();namedRanges[name]={sheetIndex:activeSheet,start,end};queueSave();showToast(`Диапазон ${name} = ${start}:${end}. Пример: =SUM(${name})`)};
document.querySelector('#traceFormulaBtn').onclick=()=>{document.querySelectorAll('.formula-trace').forEach(el=>el.classList.remove('formula-trace'));if(!active)return;const id=active.dataset.id,raw=String(getData(id).value||''),refs=[...raw.toUpperCase().matchAll(/\b([A-Z]+\d+)\b/g)].map(m=>m[1]),dependents=Object.entries(cells).filter(([,d])=>String(d.value||'').toUpperCase().match(new RegExp(`\\b${id}\\b`))).map(([cell])=>cell),all=[...new Set([...refs,...dependents])];all.forEach(cell=>document.querySelector(`[data-id="${cell}"]`)?.classList.add('formula-trace'));if(!all.length)return showToast('Связи формулы не найдены');showToast(`Связанных ячеек: ${all.length}`);setTimeout(()=>document.querySelectorAll('.formula-trace').forEach(el=>el.classList.remove('formula-trace')),5000)};
document.querySelector('#addRowBtn').onclick=()=>{captureHistory();rows++;buildSheet();renderValues();queueSave()};document.querySelector('#addColBtn').onclick=()=>{captureHistory();cols++;buildSheet();renderValues();queueSave()};
document.querySelector('#insertRowBtn').onclick=()=>{if(!active||sheets[activeSheet]?.protected)return;captureHistory();const at=cellPosition(active.dataset.id).r,next={};Object.entries(cells).forEach(([id,data])=>{const p=cellPosition(id);next[cellId(p.r>=at?p.r+1:p.r,p.c)]=data});cells=next;rows++;selectedIds=new Set([cellId(at,0)]);buildSheet();renderValues();queueSave();showToast(`Строка добавлена перед ${at+1}`)};
document.querySelector('#insertColBtn').onclick=()=>{if(!active||sheets[activeSheet]?.protected)return;captureHistory();const at=cellPosition(active.dataset.id).c,next={};Object.entries(cells).forEach(([id,data])=>{const p=cellPosition(id);next[cellId(p.r,p.c>=at?p.c+1:p.c)]=data});cells=next;cols++;selectedIds=new Set([cellId(0,at)]);buildSheet();renderValues();queueSave();showToast(`Столбец ${colName(at)} добавлен`)};
document.querySelector('#deleteRowBtn').onclick=()=>{if(rows<=1)return;captureHistory();rows--;Object.keys(cells).forEach(id=>{const m=id.match(/\d+/);if(+m[0]>rows)delete cells[id]});buildSheet();renderValues();queueSave()};
document.querySelector('#deleteColBtn').onclick=()=>{if(cols<=1)return;captureHistory();cols--;Object.keys(cells).forEach(id=>{if(lettersToNumber(id.match(/[A-Z]+/)[0])>=cols)delete cells[id]});buildSheet();renderValues();queueSave()};
document.querySelector('#clearBtn').onclick=()=>{if(!active)return;captureHistory();getData(active.dataset.id).value='';active.textContent='';formulaInput.value='';queueSave();updateStats()};
function updateStats(){const ids=selectedIds.size>1?[...selectedIds]:Object.keys(cells),nums=ids.map(id=>parseFloat(valueOf(id))).filter(Number.isFinite);const sum=nums.reduce((a,b)=>a+b,0),avg=nums.length?sum/nums.length:0,min=nums.length?Math.min(...nums):0,max=nums.length?Math.max(...nums):0;stats.textContent=`Сумма: ${round(sum)} · Среднее: ${round(avg)} · Мин: ${round(min)} · Макс: ${round(max)} · Чисел: ${nums.length}`}
const round=n=>Math.round(n*100)/100;
function workbookSnapshot(){syncSheet();return JSON.stringify({sheets,activeSheet,namedRanges})}
function captureHistory(){if(!historyReady)return;undoStack.push(workbookSnapshot());if(undoStack.length>40)undoStack.shift();redoStack=[]}
function restoreSnapshot(raw){const d=JSON.parse(raw);sheets=d.sheets;namedRanges=d.namedRanges||namedRanges;activeSheet=Math.min(d.activeSheet,sheets.length-1);({rows,cols,cells}=sheets[activeSheet]);buildSheet();renderTabs();renderValues();queueSave()}
function undo(){if(!undoStack.length)return showToast('Больше нечего отменять');redoStack.push(workbookSnapshot());restoreSnapshot(undoStack.pop());showToast('Действие отменено')}
function redo(){if(!redoStack.length)return showToast('Больше нечего повторять');undoStack.push(workbookSnapshot());restoreSnapshot(redoStack.pop());showToast('Действие повторено')}
document.querySelector('#undoBtn').onclick=undo;document.querySelector('#redoBtn').onclick=redo;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();openFind()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}else if(e.key==='Escape')document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'))});
function syncSheet(){sheets[activeSheet]={...sheets[activeSheet],rows,cols,cells}}
function queueSave(){saveStatus.textContent='Сохранение…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{syncSheet();localStorage.setItem(STORE,JSON.stringify({version:11,sheets,activeSheet,namedRanges}));maybeAutoSnapshot();saveStatus.textContent='Книга сохранена'},450)}
function download(content,name,type){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
document.querySelector('#saveBtn').onclick=()=>{syncSheet();download(JSON.stringify({app:'MyExcel 2026',version:11,sheets,namedRanges},null,2),'MyExcel-книга.json','application/json')};
document.querySelector('#csvBtn').onclick=()=>{const lines=[];for(let r=0;r<rows;r++){const line=[];for(let c=0;c<cols;c++)line.push('"'+String(valueOf(cellId(r,c))).replaceAll('"','""')+'"');lines.push(line.join(','))}download('\ufeff'+lines.join('\n'),'MyExcel-таблица.csv','text/csv;charset=utf-8')};
document.querySelector('#xlsBtn').onclick=()=>{if(!window.XLSX)return showToast('Модуль Excel ещё загружается — повторите через несколько секунд');syncSheet();const workbook=XLSX.utils.book_new();sheets.forEach((item,index)=>{const data=[];for(let r=0;r<item.rows;r++){const row=[];for(let c=0;c<item.cols;c++){const raw=item.cells?.[cellId(r,c)]?.value??'';row.push(raw)}data.push(row)}const worksheet=XLSX.utils.aoa_to_sheet(data);XLSX.utils.book_append_sheet(workbook,worksheet,(item.name||`Лист${index+1}`).slice(0,31))});XLSX.writeFile(workbook,'MyExcel-книга.xlsx');showToast('Книга XLSX сохранена')};
function escapeHtml(v){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function workbookReportHtml(){syncSheet();const sections=sheets.map((s,si)=>{let table='<table>';for(let r=0;r<s.rows;r++){table+='<tr>';for(let c=0;c<s.cols;c++){const tag=r===0?'th':'td';table+=`<${tag}>${escapeHtml(valueOfAt(si,cellId(r,c)))}</${tag}>`}table+='</tr>'}return `<section><h2>${escapeHtml(s.name)}</h2>${table}</section>`}).join('');return `<!doctype html><html lang="ru"><head><meta charset="UTF-8"><title>MyExcel — отчёт</title><style>body{font:14px Arial;margin:28px;color:#1f2937}h1{color:#107c41}section{margin:28px 0;overflow:auto;break-after:page}table{border-collapse:collapse}th,td{border:1px solid #cbd5e1;padding:7px 10px;min-width:80px}th{background:#107c41;color:white}@media print{section:last-child{break-after:auto}}</style></head><body><h1>MyExcel 2026 — отчёт</h1>${sections}</body></html>`}
document.querySelector('#htmlReportBtn').onclick=()=>download('\ufeff'+workbookReportHtml(),'MyExcel-отчёт.html','text/html;charset=utf-8');
document.querySelector('#printWorkbookBtn').onclick=()=>{const w=window.open('','_blank');if(!w)return showToast('Разрешите всплывающие окна');w.document.write(workbookReportHtml());w.document.close();w.onload=()=>w.print()};
document.addEventListener('copy',e=>{if(!active||!selectedIds.size)return;const points=[...selectedIds].map(cellPosition),r1=Math.min(...points.map(p=>p.r)),r2=Math.max(...points.map(p=>p.r)),c1=Math.min(...points.map(p=>p.c)),c2=Math.max(...points.map(p=>p.c)),lines=[];for(let r=r1;r<=r2;r++){const line=[];for(let c=c1;c<=c2;c++)line.push(getData(cellId(r,c)).value);lines.push(line.join('\t'))}e.clipboardData.setData('text/plain',lines.join('\n'));e.preventDefault();showToast('Диапазон скопирован')});
document.addEventListener('paste',e=>{if(!active||!e.clipboardData)return;const text=e.clipboardData.getData('text/plain');if(!text.includes('\t')&&!text.includes('\n'))return;captureHistory();e.preventDefault();const start=cellPosition(active.dataset.id),matrix=text.replace(/\r/g,'').split('\n').map(line=>line.split('\t'));rows=Math.max(rows,start.r+matrix.length);cols=Math.max(cols,start.c+Math.max(...matrix.map(x=>x.length)));matrix.forEach((row,r)=>row.forEach((value,c)=>getData(cellId(start.r+r,start.c+c)).value=value));buildSheet();renderValues();queueSave();showToast('Таблица вставлена')});
document.querySelector('#conditionalBtn').onclick=()=>{if(!selectedIds.size)return;captureHistory();const nums=[...selectedIds].map(id=>Number(valueOf(id))).filter(Number.isFinite),avg=nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0;selectedIds.forEach(id=>{const n=Number(valueOf(id));if(Number.isFinite(n)){getData(id).style.backgroundColor=n>=avg?'#d9ead3':'#f4cccc';getData(id).style.color=n>=avg?'#166534':'#991b1b'}});buildSheet();renderValues();queueSave();showToast('Зелёный — выше среднего, красный — ниже')};
document.querySelector('#mergeBtn').onclick=()=>{if(selectedIds.size<2||sheets[activeSheet]?.protected)return showToast('Выделите прямоугольный диапазон');const points=[...selectedIds].map(cellPosition),r1=Math.min(...points.map(p=>p.r)),r2=Math.max(...points.map(p=>p.r)),c1=Math.min(...points.map(p=>p.c)),c2=Math.max(...points.map(p=>p.c));if(selectedIds.size!==(r2-r1+1)*(c2-c1+1))return showToast('Нужен прямоугольный диапазон');if([...selectedIds].some(id=>getData(id).merge||getData(id).mergeParent))return showToast('В диапазоне уже есть объединение');captureHistory();const parent=cellId(r1,c1);getData(parent).merge={rows:r2-r1+1,cols:c2-c1+1};selectedIds.forEach(id=>{if(id!==parent)getData(id).mergeParent=parent});selectedIds=new Set([parent]);buildSheet();renderValues();queueSave();showToast('Ячейки объединены')};
document.querySelector('#unmergeBtn').onclick=()=>{if(!active)return;const data=getData(active.dataset.id),parent=data.mergeParent||active.dataset.id,merge=getData(parent).merge;if(!merge)return showToast('Ячейка не объединена');captureHistory();const start=cellPosition(parent);for(let r=start.r;r<start.r+merge.rows;r++)for(let c=start.c;c<start.c+merge.cols;c++)delete getData(cellId(r,c)).mergeParent;delete getData(parent).merge;buildSheet();renderValues();queueSave();showToast('Ячейки разъединены')};
document.querySelector('#fillSeriesBtn').onclick=()=>{const points=[...selectedIds].map(cellPosition).sort((a,b)=>a.r-b.r||a.c-b.c);if(points.length<2)return showToast('Выделите два числа последовательности');const vertical=points.every(p=>p.c===points[0].c),horizontal=points.every(p=>p.r===points[0].r);if(!vertical&&!horizontal)return showToast('Выделите числа в одной строке или столбце');const first=Number(valueOf(cellId(points[0].r,points[0].c))),second=Number(valueOf(cellId(points[1].r,points[1].c)));if(!Number.isFinite(first)||!Number.isFinite(second))return showToast('Первые две ячейки должны содержать числа');const count=Math.max(1,Math.min(100,Number(prompt('Сколько следующих значений добавить?',5))||0));if(!count)return;captureHistory();const step=second-first,last=points.at(-1),lastValue=Number(valueOf(cellId(last.r,last.c)));for(let i=1;i<=count;i++){const r=last.r+(vertical?i:0),c=last.c+(horizontal?i:0);rows=Math.max(rows,r+1);cols=Math.max(cols,c+1);getData(cellId(r,c)).value=String(lastValue+step*i)}buildSheet();renderValues();queueSave();showToast('Последовательность продолжена')};
document.querySelector('#colorScaleBtn').onclick=()=>{const numeric=[...selectedIds].map(id=>[id,Number(valueOf(id))]).filter(([,v])=>Number.isFinite(v));if(!numeric.length)return showToast('В выделении нет чисел');captureHistory();const values=numeric.map(([,v])=>v),min=Math.min(...values),max=Math.max(...values);numeric.forEach(([id,v])=>{const t=(max===min)?0.5:(v-min)/(max-min),r=Math.round(239+(34-239)*t),g=Math.round(68+(197-68)*t),b=Math.round(68+(94-68)*t);getData(id).style.backgroundColor=`rgb(${r},${g},${b})`;getData(id).style.color=t>.35&&t<.8?'#111827':'#ffffff'});buildSheet();renderValues();queueSave();showToast('Цветовая шкала применена')};
document.querySelector('#dataBarsBtn').onclick=()=>{const numeric=[...selectedIds].map(id=>[id,Number(valueOf(id))]).filter(([,v])=>Number.isFinite(v));if(!numeric.length)return showToast('В выделении нет чисел');captureHistory();const values=numeric.map(([,v])=>v),min=Math.min(0,...values),max=Math.max(...values,1);numeric.forEach(([id,v])=>{const percent=Math.max(0,Math.min(100,(v-min)/(max-min)*100));getData(id).style.background=`linear-gradient(90deg,#86efac ${percent}%,transparent ${percent}%)`});buildSheet();renderValues();queueSave();showToast('Полосы данных добавлены')};
document.querySelector('#linkBtn').onclick=()=>{if(!active||sheets[activeSheet]?.protected)return;const data=getData(active.dataset.id),url=(prompt('Адрес ссылки:',data.link||'https://')||'').trim();if(!url)return;const safe=/^https?:\/\//i.test(url)?url:'https://'+url,label=prompt('Текст ссылки:',data.value||'Открыть ссылку');captureHistory();data.link=safe;if(label!==null)data.value=label;buildSheet();renderValues();queueSave();showToast('Ссылка добавлена — откройте двойным нажатием')};
document.querySelector('#transposeBtn').onclick=()=>{if(!selectedIds.size||sheets[activeSheet]?.protected)return;const destination=(prompt('Вставить транспонированную таблицу начиная с ячейки:',active?.dataset.id||'A1')||'').trim().toUpperCase();if(!/^[A-Z]+\d+$/.test(destination))return destination&&showToast('Введите адрес, например D1');const points=[...selectedIds].map(cellPosition),r1=Math.min(...points.map(p=>p.r)),r2=Math.max(...points.map(p=>p.r)),c1=Math.min(...points.map(p=>p.c)),c2=Math.max(...points.map(p=>p.c)),matrix=[];for(let r=r1;r<=r2;r++){const row=[];for(let c=c1;c<=c2;c++)row.push(JSON.parse(JSON.stringify(cells[cellId(r,c)]||{value:'',style:{}})));matrix.push(row)}const start=cellPosition(destination);captureHistory();matrix.forEach((row,r)=>row.forEach((data,c)=>{cells[cellId(start.r+c,start.c+r)]=data}));rows=Math.max(rows,start.r+c2-c1+2);cols=Math.max(cols,start.c+r2-r1+2);buildSheet();renderValues();queueSave();showToast('Таблица транспонирована')};
document.querySelector('#selectionCsvBtn').onclick=()=>{if(!selectedIds.size)return;const points=[...selectedIds].map(cellPosition),r1=Math.min(...points.map(p=>p.r)),r2=Math.max(...points.map(p=>p.r)),c1=Math.min(...points.map(p=>p.c)),c2=Math.max(...points.map(p=>p.c)),lines=[];for(let r=r1;r<=r2;r++){const line=[];for(let c=c1;c<=c2;c++)line.push('"'+String(valueOf(cellId(r,c))).replaceAll('"','""')+'"');lines.push(line.join(','))}download('\ufeff'+lines.join('\n'),`${sheets[activeSheet].name}-${cellId(r1,c1)}-${cellId(r2,c2)}.csv`,'text/csv;charset=utf-8')};
document.querySelector('#checkboxBtn').onclick=()=>{if(!selectedIds.size||sheets[activeSheet]?.protected)return;captureHistory();selectedIds.forEach(id=>{const d=getData(id);d.type='checkbox';d.checked=d.checked??false;d.value=d.checked?'TRUE':'FALSE'});buildSheet();renderValues();queueSave();showToast('Флажок добавлен')};
document.querySelector('#autoWidthBtn').onclick=()=>{let longest=8;Object.values(cells).forEach(d=>longest=Math.max(longest,String(d.value||'').length));const width=Math.min(240,Math.max(85,longest*8+22));sheet.style.setProperty('--cell-width',width+'px');showToast(`Ширина: ${width} px`)};
document.querySelector('#freezeBtn').onclick=()=>{captureHistory();sheets[activeSheet].freezeFirstRow=!sheets[activeSheet].freezeFirstRow;buildSheet();renderValues();queueSave();showToast(sheets[activeSheet].freezeFirstRow?'Первая строка закреплена':'Закрепление снято')};
document.querySelector('#freezeSelectedRowBtn').onclick=()=>{if(!active)return;captureHistory();const r=cellPosition(active.dataset.id).r;sheets[activeSheet].freezeRow=sheets[activeSheet].freezeRow===r?null:r;buildSheet();renderValues();queueSave();showToast(sheets[activeSheet].freezeRow===r?`Строка ${r+1} закреплена`:'Закрепление снято')};
document.querySelector('#freezeColBtn').onclick=()=>{captureHistory();sheets[activeSheet].freezeFirstCol=!sheets[activeSheet].freezeFirstCol;buildSheet();renderValues();queueSave();showToast(sheets[activeSheet].freezeFirstCol?'Первый столбец закреплён':'Закрепление столбца снято')};
document.querySelector('#copyStyleBtn').onclick=()=>{if(!active)return;copiedStyle=JSON.parse(JSON.stringify(getData(active.dataset.id).style||{}));showToast('Оформление скопировано')};document.querySelector('#pasteStyleBtn').onclick=()=>{if(!copiedStyle)return showToast('Сначала скопируйте оформление');captureHistory();selectedIds.forEach(id=>getData(id).style=JSON.parse(JSON.stringify(copiedStyle)));buildSheet();renderValues();queueSave();showToast('Оформление применено')};document.querySelector('#clearStyleBtn').onclick=()=>{captureHistory();selectedIds.forEach(id=>getData(id).style={});buildSheet();renderValues();queueSave();showToast('Оформление очищено')};
document.querySelector('#protectBtn').onclick=()=>{captureHistory();sheets[activeSheet].protected=!sheets[activeSheet].protected;buildSheet();renderValues();queueSave();document.querySelector('#protectBtn').textContent=sheets[activeSheet].protected?'🔓 Снять защиту':'🔒 Защита';showToast(sheets[activeSheet].protected?'Лист защищён от изменений':'Редактирование разрешено')};
document.querySelector('#fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>showToast('Полный экран недоступен'));else document.exitFullscreen?.()};
document.querySelector('#newBtn').onclick=()=>{if(!confirm('Создать новую книгу?'))return;rows=30;cols=12;cells={};namedRanges={};sheets=[{name:'Лист1',rows,cols,cells}];activeSheet=0;buildSheet();renderTabs();queueSave();updateStats()};
document.querySelector('#openBtn').onclick=()=>document.querySelector('#fileInput').click();document.querySelector('#fileInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const lower=file.name.toLowerCase(),reader=new FileReader();reader.onload=()=>{try{if(lower.endsWith('.xlsx')||lower.endsWith('.xls')){if(!window.XLSX)throw Error('XLSX module');const workbook=XLSX.read(reader.result,{type:'array',cellFormula:true});sheets=workbook.SheetNames.map(name=>{const ws=workbook.Sheets[name],range=ws['!ref']?XLSX.utils.decode_range(ws['!ref']):{s:{r:0,c:0},e:{r:29,c:11}},sheetCells={};for(let r=range.s.r;r<=range.e.r;r++)for(let c=range.s.c;c<=range.e.c;c++){const source=ws[XLSX.utils.encode_cell({r,c})];if(source)sheetCells[cellId(r,c)]={value:source.f?'='+source.f:String(source.v??''),style:{}}}return{name,rows:Math.max(30,range.e.r+1),cols:Math.max(12,range.e.c+1),cells:sheetCells}});namedRanges={};activeSheet=0;({rows,cols,cells}=sheets[0])}else if(lower.endsWith('.json')){const d=JSON.parse(reader.result);sheets=Array.isArray(d.sheets)?d.sheets:[{name:'Лист1',rows:d.rows||30,cols:d.cols||12,cells:d.cells||{}}];namedRanges=d.namedRanges||{};activeSheet=0;({rows,cols,cells}=sheets[0])}else{cells={};namedRanges={};const lines=reader.result.replace(/^\ufeff/,'').split(/\r?\n/);rows=Math.max(30,lines.length);cols=12;lines.forEach((line,r)=>line.split(',').forEach((v,c)=>{cols=Math.max(cols,c+1);getData(cellId(r,c)).value=v.replace(/^"|"$/g,'').replaceAll('""','"')}));sheets=[{name:'Лист1',rows,cols,cells}];activeSheet=0}buildSheet();renderTabs();renderValues();queueSave();updateStats();showToast('Книга открыта')}catch{showToast('Не удалось открыть файл. Проверьте его формат')}};if(lower.endsWith('.xlsx')||lower.endsWith('.xls'))reader.readAsArrayBuffer(file);else reader.readAsText(file);e.target.value=''};
document.querySelector('#themeBtn').onclick=e=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');e.currentTarget.title=dark?'Светлая таблица':'Тёмная таблица';localStorage.setItem('myexcel-theme',dark?'dark':'light')};
function renderTabs(){const list=document.querySelector('#sheetTabsList');list.innerHTML='';sheets.forEach((s,i)=>{if(s.hidden)return;const b=make('button','sheet-tab'+(i===activeSheet?' active':''),s.name);if(s.tabColor)b.style.borderTop=`4px solid ${s.tabColor}`;b.title='Двойное нажатие — переименовать';b.onclick=()=>switchSheet(i);b.ondblclick=()=>{const name=prompt('Название листа:',s.name)?.trim();if(name){s.name=name.slice(0,25);renderTabs();queueSave()}};list.append(b)})}
function switchSheet(i){syncSheet();activeSheet=i;({rows,cols,cells}=sheets[i]);buildSheet();renderTabs();renderValues();document.querySelector('[data-id="A1"]')?.focus()}
document.querySelector('#addSheetBtn').onclick=()=>{captureHistory();syncSheet();let n=1;while(sheets.some(s=>s.name===`Лист${n}`))n++;sheets.push({name:`Лист${n}`,rows:30,cols:12,cells:{}});switchSheet(sheets.length-1);queueSave()};
document.querySelector('#previousSheet').onclick=()=>{const visible=sheets.map((s,i)=>s.hidden?null:i).filter(i=>i!==null),pos=visible.indexOf(activeSheet);switchSheet(visible[(pos-1+visible.length)%visible.length])};
document.querySelector('#sheetColorBtn').onclick=()=>document.querySelector('#sheetColorInput').click();document.querySelector('#sheetColorInput').oninput=e=>{captureHistory();sheets[activeSheet].tabColor=e.target.value;renderTabs();queueSave()};
document.querySelector('#hideSheetBtn').onclick=()=>{if(sheets.filter(s=>!s.hidden).length<=1)return showToast('Нельзя скрыть единственный видимый лист');captureHistory();sheets[activeSheet].hidden=true;const next=sheets.findIndex(s=>!s.hidden);switchSheet(next);queueSave();showToast('Лист скрыт')};
document.querySelector('#showSheetsBtn').onclick=()=>{const hidden=sheets.map((s,i)=>s.hidden?{s,i}:null).filter(Boolean);if(!hidden.length)return showToast('Скрытых листов нет');const answer=prompt('Введите номер листа, который нужно показать:\n'+hidden.map((x,n)=>`${n+1}. ${x.s.name}`).join('\n'));const item=hidden[Number(answer)-1];if(!item)return;captureHistory();item.s.hidden=false;renderTabs();queueSave();showToast('Лист снова отображается')};
document.querySelector('#duplicateSheetBtn').onclick=()=>{captureHistory();syncSheet();const copy=JSON.parse(JSON.stringify(sheets[activeSheet]));copy.name=(copy.name+' копия').slice(0,25);sheets.splice(activeSheet+1,0,copy);switchSheet(activeSheet+1);queueSave();showToast('Лист скопирован')};
document.querySelector('#deleteSheetBtn').onclick=()=>{if(sheets.length===1)return showToast('Нельзя удалить единственный лист');if(!confirm(`Удалить лист «${sheets[activeSheet].name}»?`))return;captureHistory();sheets.splice(activeSheet,1);activeSheet=Math.min(activeSheet,sheets.length-1);({rows,cols,cells}=sheets[activeSheet]);buildSheet();renderTabs();renderValues();queueSave()};
function sortSheet(direction){if(!active)return showToast('Сначала выберите ячейку в нужном столбце');captureHistory();const column=lettersToNumber(active.dataset.id.match(/[A-Z]+/)[0]),matrix=[];for(let r=0;r<rows;r++){const row=[];for(let c=0;c<cols;c++)row.push(JSON.parse(JSON.stringify(cells[cellId(r,c)]||{value:'',style:{}})));matrix.push(row)}matrix.sort((a,b)=>{const av=a[column].value,bv=b[column].value,an=Number(av),bn=Number(bv),result=Number.isFinite(an)&&Number.isFinite(bn)?an-bn:String(av).localeCompare(String(bv),'ru',{numeric:true});return direction==='asc'?result:-result});cells={};matrix.forEach((row,r)=>row.forEach((data,c)=>{if(data.value||Object.keys(data.style||{}).length)cells[cellId(r,c)]=data}));buildSheet();renderValues();queueSave();showToast(direction==='asc'?'Отсортировано по возрастанию':'Отсортировано по убыванию')}
document.querySelector('#sortAscBtn').onclick=()=>sortSheet('asc');document.querySelector('#sortDescBtn').onclick=()=>sortSheet('desc');
document.querySelector('#dedupeBtn').onclick=()=>{if(!active)return showToast('Выберите столбец');const column=cellPosition(active.dataset.id).c,seen=new Set(),keep=[0];for(let r=1;r<rows;r++){const value=String(valueOf(cellId(r,column))).trim().toLowerCase();if(!value||!seen.has(value)){keep.push(r);if(value)seen.add(value)}}const removed=rows-keep.length;if(!removed)return showToast('Дубликаты не найдены');if(!confirm(`Удалить повторяющиеся строки: ${removed}?`))return;captureHistory();const next={};keep.forEach((oldR,newR)=>{for(let c=0;c<cols;c++){const data=cells[cellId(oldR,c)];if(data)next[cellId(newR,c)]=data}});cells=next;rows=keep.length;buildSheet();renderValues();queueSave();showToast(`Удалено строк: ${removed}`)};
function applyFilter(){const filter=sheets[activeSheet]?.filter;if(!filter?.query)return;const query=filter.query.toLowerCase(),heads=document.querySelectorAll('.row-head');for(let r=1;r<rows;r++){const visible=String(valueOf(cellId(r,filter.col))).toLowerCase().includes(query);if(heads[r])heads[r].style.visibility=visible?'':'hidden';document.querySelectorAll('.cell').forEach(el=>{if(cellPosition(el.dataset.id).r===r)el.style.visibility=visible?'':'hidden'})}}
document.querySelector('#filterBtn').onclick=()=>{if(!active)return showToast('Выберите столбец для фильтра');const query=prompt('Показывать строки, содержащие:');if(query===null)return;captureHistory();sheets[activeSheet].filter={col:cellPosition(active.dataset.id).c,query:query.trim()};buildSheet();renderValues();queueSave();showToast(query.trim()?'Фильтр включён':'Фильтр очищен')};
document.querySelector('#clearFilterBtn').onclick=()=>{if(!sheets[activeSheet].filter)return showToast('Фильтр не включён');captureHistory();delete sheets[activeSheet].filter;buildSheet();renderValues();queueSave();showToast('Фильтр очищен')};
document.querySelector('#validationBtn').onclick=()=>{if(!selectedIds.size||sheets[activeSheet]?.protected)return showToast('Выберите ячейки и снимите защиту');const answer=prompt('Введите варианты списка через запятую:');if(answer===null)return;const options=[...new Set(answer.split(',').map(v=>v.trim()).filter(Boolean))];if(!options.length)return showToast('Добавьте хотя бы один вариант');captureHistory();selectedIds.forEach(id=>getData(id).validation=options);buildSheet();renderValues();queueSave();showToast('Выпадающий список добавлен — двойное нажатие для выбора')};
const statsModal=document.querySelector('#statsModal');document.querySelector('#bookStatsBtn').onclick=()=>{syncSheet();let filled=0,formulas=0,comments=0,errors=0;sheets.forEach((s,si)=>Object.entries(s.cells||{}).forEach(([id,d])=>{if(d.value!==''||d.type==='checkbox')filled++;if(String(d.value||'').startsWith('='))formulas++;if(d.note)comments++;if(String(valueOfAt(si,id)).startsWith('#'))errors++}));const cards=[['Листов',sheets.length],['Заполнено ячеек',filled],['Формул',formulas],['Комментариев',comments],['Ошибок формул',errors],['Активный лист',sheets[activeSheet].name]];document.querySelector('#bookStatsGrid').innerHTML=cards.map(([label,value])=>`<div><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`).join('');statsModal.classList.remove('hidden')};document.querySelector('#closeStatsBtn').onclick=()=>statsModal.classList.add('hidden');statsModal.onclick=e=>{if(e.target===statsModal)statsModal.classList.add('hidden')};
document.querySelector('#printBtn').onclick=()=>window.print();
function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)}
document.querySelector('#zoom').oninput=e=>{sheet.style.zoom=e.target.value/100;document.querySelector('#zoomOut').value=e.target.value+'%'};
const modal=document.querySelector('#chartModal');document.querySelector('#chartBtn').onclick=()=>modal.classList.remove('hidden');document.querySelector('#closeChartBtn').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};document.querySelector('#buildChartBtn').onclick=drawChart;
const findModal=document.querySelector('#findModal');let findCursor=-1;function openFind(){findModal.classList.remove('hidden');setTimeout(()=>document.querySelector('#findText').focus(),30)}document.querySelector('#findBtn').onclick=openFind;document.querySelector('#closeFindBtn').onclick=()=>findModal.classList.add('hidden');findModal.onclick=e=>{if(e.target===findModal)findModal.classList.add('hidden')};
function matches(){const q=document.querySelector('#findText').value.toLowerCase();if(!q)return[];const indexes=document.querySelector('#searchWorkbook').checked?sheets.map((_,i)=>i):[activeSheet],out=[];indexes.forEach(si=>Object.keys(sheets[si].cells||{}).filter(id=>String(sheets[si].cells[id].value).toLowerCase().includes(q)).sort().forEach(id=>out.push({si,id})));return out}
function findNext(){const list=matches();if(!list.length){document.querySelector('#findResult').textContent='Ничего не найдено';return}findCursor=(findCursor+1)%list.length;const item=list[findCursor];if(item.si!==activeSheet)switchSheet(item.si);findModal.classList.add('hidden');setTimeout(()=>document.querySelector(`[data-id="${item.id}"]`)?.focus(),20);document.querySelector('#findResult').textContent=`Найдено: ${list.length} · ${sheets[item.si].name}!${item.id}`}
document.querySelector('#findNextBtn').onclick=findNext;document.querySelector('#replaceBtn').onclick=()=>{const list=matches();if(!list.length)return showToast('Ничего не найдено');captureHistory();const item=list[Math.max(0,findCursor)%list.length],q=document.querySelector('#findText').value,repl=document.querySelector('#replaceText').value,d=sheets[item.si].cells[item.id];d.value=String(d.value).replace(q,repl);if(item.si!==activeSheet)switchSheet(item.si);buildSheet();renderValues();queueSave();showToast('Значение заменено')};document.querySelector('#replaceAllBtn').onclick=()=>{const list=matches();if(!list.length)return showToast('Ничего не найдено');captureHistory();const q=document.querySelector('#findText').value,repl=document.querySelector('#replaceText').value;list.forEach(item=>{const d=sheets[item.si].cells[item.id];d.value=String(d.value).split(q).join(repl)});({rows,cols,cells}=sheets[activeSheet]);buildSheet();renderValues();queueSave();document.querySelector('#findResult').textContent=`Заменено: ${list.length}`};
const noteModal=document.querySelector('#noteModal');function openNote(){if(!active)return showToast('Выберите ячейку');const id=active.dataset.id;document.querySelector('#noteCellName').textContent=`Ячейка ${id}`;document.querySelector('#noteText').value=getData(id).note||'';noteModal.dataset.cell=id;noteModal.classList.remove('hidden');setTimeout(()=>document.querySelector('#noteText').focus(),30)}document.querySelector('#noteBtn').onclick=openNote;document.querySelector('#closeNoteBtn').onclick=()=>noteModal.classList.add('hidden');noteModal.onclick=e=>{if(e.target===noteModal)noteModal.classList.add('hidden')};document.querySelector('#saveNoteBtn').onclick=()=>{if(sheets[activeSheet]?.protected)return showToast('Сначала снимите защиту листа');captureHistory();getData(noteModal.dataset.cell).note=document.querySelector('#noteText').value.trim();noteModal.classList.add('hidden');buildSheet();renderValues();queueSave();showToast('Комментарий сохранён')};document.querySelector('#deleteNoteBtn').onclick=()=>{if(sheets[activeSheet]?.protected)return showToast('Сначала снимите защиту листа');captureHistory();getData(noteModal.dataset.cell).note='';noteModal.classList.add('hidden');buildSheet();renderValues();queueSave();showToast('Комментарий удалён')};
const templatesModal=document.querySelector('#templatesModal');document.querySelector('#templatesBtn').onclick=()=>templatesModal.classList.remove('hidden');document.querySelector('#closeTemplatesBtn').onclick=()=>templatesModal.classList.add('hidden');templatesModal.onclick=e=>{if(e.target===templatesModal)templatesModal.classList.add('hidden')};document.querySelectorAll('[data-template]').forEach(btn=>btn.onclick=()=>applyTemplate(btn.dataset.template));
function put(r,c,value,style={}){cells[cellId(r,c)]={value:String(value),style}}
function applyTemplate(type){if(Object.values(cells).some(d=>d.value)&&!confirm('Заменить содержимое текущего листа шаблоном?'))return;captureHistory();cells={};rows=30;cols=12;const head={fontWeight:'bold',backgroundColor:'#107c41',color:'#ffffff',textAlign:'center'};if(type==='budget'){sheets[activeSheet].name='Месячный бюджет';['Дата','Категория','Доход, ₸','Расход, ₸','Комментарий'].forEach((v,c)=>put(0,c,v,head));put(0,6,'Доходы',head);put(1,6,'Расходы',head);put(2,6,'Остаток',head);put(0,7,'=SUM(C2:C30)',{format:'currency',fontWeight:'bold'});put(1,7,'=SUM(D2:D30)',{format:'currency'});put(2,7,'=H1-H2',{format:'currency',fontWeight:'bold'})}else if(type==='portfolio'){sheets[activeSheet].name='Портфель акций';['Тикер','Компания','Цена покупки','Количество','Вложено, ₸','Текущая цена','Стоимость, ₸','Результат, ₸'].forEach((v,c)=>put(0,c,v,head));for(let r=1;r<15;r++){put(r,4,`=C${r+1}*D${r+1}`,{format:'currency'});put(r,6,`=F${r+1}*D${r+1}`,{format:'currency'});put(r,7,`=G${r+1}-E${r+1}`,{format:'currency'})}}else{sheets[activeSheet].name='Мясо разбор';['Дата','Приход','Брутто, кг','Чистый выход, кг','Отход, кг','Выход, %','Комментарий'].forEach((v,c)=>put(0,c,v,head));for(let r=1;r<20;r++)put(r,5,`=D${r+1}/C${r+1}*100`,{format:'percent'})}templatesModal.classList.add('hidden');selectedIds=new Set(['A1']);syncSheet();buildSheet();renderTabs();renderValues();queueSave();showToast('Шаблон создан')}
function drawChart(){const m=document.querySelector('#chartRange').value.toUpperCase().replace(/\s/g,'').match(/^([A-Z]+\d+):([A-Z]+\d+)$/);if(!m)return showToast('Укажите диапазон, например A1:B6');const a=m[1].match(/([A-Z]+)(\d+)/),b=m[2].match(/([A-Z]+)(\d+)/),r1=Math.min(+a[2],+b[2])-1,r2=Math.max(+a[2],+b[2])-1,c1=Math.min(lettersToNumber(a[1]),lettersToNumber(b[1])),c2=Math.max(lettersToNumber(a[1]),lettersToNumber(b[1]));if(c2-c1<1)return showToast('Нужно минимум два столбца');const labels=[],values=[];for(let r=r1;r<=r2;r++){labels.push(String(valueOf(cellId(r,c1)))||`Строка ${r+1}`);values.push(Number(valueOf(cellId(r,c1+1)))||0)}paintChart(labels,values,document.querySelector('#chartType').value)}
function paintChart(labels,values,type){const canvas=document.querySelector('#chartCanvas'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=45,colors=['#107c41','#4f8cff','#f59e0b','#e05260','#8b5cf6','#14b8a6','#ec4899'],max=Math.max(...values.map(Math.abs),1);ctx.clearRect(0,0,w,h);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--surface');ctx.fillRect(0,0,w,h);ctx.font='13px Segoe UI';ctx.textAlign='center';if(type==='pie'){const total=values.reduce((a,b)=>a+Math.max(0,b),0)||1;let angle=-Math.PI/2;values.forEach((v,i)=>{const next=angle+Math.max(0,v)/total*Math.PI*2;ctx.beginPath();ctx.moveTo(w/2,h/2);ctx.arc(w/2,h/2,Math.min(w,h)*.38,angle,next);ctx.fillStyle=colors[i%colors.length];ctx.fill();angle=next})}else{ctx.strokeStyle='#94a3b8';ctx.beginPath();ctx.moveTo(p,p);ctx.lineTo(p,h-p);ctx.lineTo(w-p,h-p);ctx.stroke();const gap=(w-p*2)/Math.max(values.length,1);if(type==='line'){ctx.strokeStyle=colors[0];ctx.lineWidth=3;ctx.beginPath();values.forEach((v,i)=>{const x=p+gap*(i+.5),y=h-p-(v/max)*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle=colors[0];ctx.fillRect(x-4,y-4,8,8)});ctx.stroke()}else values.forEach((v,i)=>{const bh=(v/max)*(h-p*2),x=p+gap*i+gap*.18;ctx.fillStyle=colors[i%colors.length];ctx.fillRect(x,h-p-bh,gap*.64,bh)});ctx.fillStyle='#64748b';labels.forEach((l,i)=>ctx.fillText(l.slice(0,10),p+gap*(i+.5),h-18))}document.querySelector('#chartLegend').innerHTML=labels.map((l,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${String(l).replace(/[&<>]/g,'')}: ${round(values[i])}</span>`).join('')}
function loadSnapshots(){try{return JSON.parse(localStorage.getItem(SNAPSHOTS)||'[]')}catch{return[]}}
function createSnapshot(manual=false){syncSheet();const list=loadSnapshots();list.unshift({time:new Date().toISOString(),data:JSON.stringify({sheets,activeSheet,namedRanges})});try{localStorage.setItem(SNAPSHOTS,JSON.stringify(list.slice(0,6)));localStorage.setItem(SNAPSHOTS+'-last',String(Date.now()));if(manual){renderSnapshots();showToast('Снимок книги создан')}}catch{if(manual)showToast('Недостаточно места для снимка')}}
function maybeAutoSnapshot(){const last=Number(localStorage.getItem(SNAPSHOTS+'-last')||0);if(Date.now()-last>300000)createSnapshot(false)}
const snapshotsModal=document.querySelector('#snapshotsModal');function renderSnapshots(){const list=loadSnapshots(),box=document.querySelector('#snapshotList');box.innerHTML=list.length?list.map((s,i)=>`<div class="snapshot-item"><div><b>Версия ${i+1}</b><br><small>${escapeHtml(new Date(s.time).toLocaleString('ru-RU'))}</small></div><button data-restore-snapshot="${i}">Восстановить</button></div>`).join(''):'<p class="chart-help">Снимков пока нет.</p>';box.querySelectorAll('[data-restore-snapshot]').forEach(btn=>btn.onclick=()=>{if(!confirm('Восстановить эту версию книги?'))return;const saved=JSON.parse(loadSnapshots()[Number(btn.dataset.restoreSnapshot)].data);sheets=saved.sheets;namedRanges=saved.namedRanges||{};activeSheet=Math.min(saved.activeSheet||0,sheets.length-1);({rows,cols,cells}=sheets[activeSheet]);buildSheet();renderTabs();renderValues();queueSave();snapshotsModal.classList.add('hidden');showToast('Версия восстановлена')})}
document.querySelector('#snapshotsBtn').onclick=()=>{renderSnapshots();snapshotsModal.classList.remove('hidden')};document.querySelector('#closeSnapshotsBtn').onclick=()=>snapshotsModal.classList.add('hidden');document.querySelector('#createSnapshotBtn').onclick=()=>createSnapshot(true);snapshotsModal.onclick=e=>{if(e.target===snapshotsModal)snapshotsModal.classList.add('hidden')};
const commandModal=document.querySelector('#commandModal'),commandSearch=document.querySelector('#commandSearch');const commands=[['Найти и заменить','findBtn','Ctrl+F'],['Быстрая сумма','quickSumBtn','SUM'],['Среднее значение','quickAvgBtn','AVERAGE'],['Создать диаграмму','chartBtn',''],['Именованный диапазон','namedRangeBtn',''],['Проверить связи формулы','traceFormulaBtn',''],['Добавить ссылку','linkBtn',''],['Транспонировать таблицу','transposeBtn',''],['Экспорт диапазона CSV','selectionCsvBtn',''],['Статистика книги','bookStatsBtn',''],['Резервные версии','snapshotsBtn',''],['Тёмная тема','themeBtn','']];function renderCommands(){const q=commandSearch.value.toLowerCase(),list=commands.filter(c=>c[0].toLowerCase().includes(q));document.querySelector('#commandList').innerHTML=list.map(c=>`<button data-command-id="${c[1]}"><span>${c[0]}</span><small>${c[2]}</small></button>`).join('');document.querySelectorAll('[data-command-id]').forEach(btn=>btn.onclick=()=>{commandModal.classList.add('hidden');document.querySelector('#'+btn.dataset.commandId)?.click()})}function openCommands(){commandSearch.value='';renderCommands();commandModal.classList.remove('hidden');setTimeout(()=>commandSearch.focus(),20)}document.querySelector('#commandBtn').onclick=openCommands;commandSearch.oninput=renderCommands;commandSearch.onkeydown=e=>{if(e.key==='Enter')document.querySelector('#commandList button')?.click()};commandModal.onclick=e=>{if(e.target===commandModal)commandModal.classList.add('hidden')};
function closeMacMenus(){document.querySelectorAll('.dropdown-menu,.mac-menu-button').forEach(el=>el.classList.remove('open'))}
document.querySelectorAll('.mac-menu-button[data-menu]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const panel=document.querySelector(`[data-menu-panel="${btn.dataset.menu}"]`),opening=!panel.classList.contains('open');closeMacMenus();if(opening){btn.classList.add('open');panel.classList.add('open')}});
document.querySelectorAll('.dropdown-menu').forEach(menu=>menu.onclick=e=>e.stopPropagation());document.querySelectorAll('.dropdown-menu button').forEach(btn=>btn.addEventListener('click',()=>setTimeout(closeMacMenus,0)));document.addEventListener('click',closeMacMenus);
function switchRibbon(name){document.querySelectorAll('[data-ribbon-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.ribbonTab===name));document.querySelectorAll('[data-ribbon]').forEach(pane=>pane.classList.toggle('active',pane.dataset.ribbon===name));document.querySelector('#ribbonHost').classList.remove('collapsed')}
document.querySelectorAll('[data-ribbon-tab]').forEach(btn=>btn.onclick=()=>switchRibbon(btn.dataset.ribbonTab));document.querySelectorAll('[data-ribbon-open]').forEach(btn=>btn.onclick=()=>{switchRibbon(btn.dataset.ribbonOpen);closeMacMenus()});
document.querySelectorAll('[data-trigger]').forEach(btn=>btn.onclick=()=>{closeMacMenus();document.querySelector('#'+btn.dataset.trigger)?.click()});
document.querySelectorAll('[data-placeholder]').forEach(btn=>btn.onclick=()=>{closeMacMenus();showToast(btn.dataset.placeholder)});
document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>{const action=btn.dataset.action;if(action==='toggle-ribbon')document.querySelector('#ribbonHost').classList.toggle('collapsed');if(action==='toggle-formula')document.querySelector('.formula-bar').classList.toggle('collapsed');if(action==='toggle-grid')sheet.classList.toggle('grid-hidden');closeMacMenus()});
document.querySelector('#helpSearch').onkeydown=e=>{if(e.key==='Enter'){closeMacMenus();openCommands();commandSearch.value=e.currentTarget.value;renderCommands()}};
function restore(){try{const d=JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('myexcel2026-workbook'));if(d){sheets=Array.isArray(d.sheets)?d.sheets:[{name:'Лист1',rows:d.rows||30,cols:d.cols||12,cells:d.cells||{}}];namedRanges=d.namedRanges||{};activeSheet=Math.min(d.activeSheet||0,sheets.length-1);({rows,cols,cells}=sheets[activeSheet])}}catch{}if(localStorage.getItem('myexcel-theme')==='dark')document.body.classList.add('dark');buildSheet();renderTabs();renderValues();updateStats();document.querySelector('[data-id="A1"]').focus();historyReady=true}
restore();
